;; The live image's authority surface is a committed list. Widening it is a
;; deliberate edit to test/authority-allowlist.txt, never a side effect.
(use-modules (srfi srfi-64) (srfi srfi-1) (ice-9 textual-ports) (live-agent generation))

(test-begin "authority")

(define allowlist
  (filter (lambda (l) (not (string-null? l)))
          (string-split (call-with-input-file "test/authority-allowlist.txt" get-string-all) #\newline)))
(define bindings (map symbol->string (@@ (live-agent generation) safe-bindings)))
(test-equal "the sandbox exposes exactly the committed bindings" allowlist bindings)

(define module ((@@ (live-agent generation) fresh-module)))
(define (reachable? form)
  (catch #t (lambda () (eval form module) #t) (lambda _ #f)))
(for-each
 (lambda (probe)
   (test-assert (string-append "unreachable from live code: " (car probe))
     (not (reachable? (cdr probe)))))
 `(("module reference syntax" . (@ (guile) system*))
   ("private module reference" . (@@ (live-agent generation) fresh-module))
   ("primitive-eval" . (primitive-eval '1))
   ("eval" . (eval '1 (interaction-environment)))
   ("module-ref" . (module-ref (resolve-module '(guile)) 'system*))
   ("the-environment" . (the-environment))
   ("current-module" . (current-module))
   ("load" . (load "/dev/null"))
   ("include" . (include "/dev/null"))
   ("use-modules" . (use-modules (ice-9 popen)))
   ("define-module" . (define-module (escape)))
   ("open-file" . (open-file "/etc/hosts" "r"))
   ("open-input-file" . (open-input-file "/etc/hosts"))
   ("getenv" . (getenv "HOME"))
   ("setenv" . (setenv "X" "1"))
   ("system" . (system "true"))
   ("system*" . (system* "true"))
   ("spawn" . (spawn "true" '("true")))
   ("open-pipe" . (open-pipe "true" OPEN_READ))
   ("delete-file" . (delete-file "/nonexistent"))
   ("mkdir" . (mkdir "/tmp/escape"))
   ("call/cc" . (call-with-current-continuation (lambda (k) 1)))
   ("dynamic-link" . (dynamic-link "libc"))
   ("exit" . (exit 0))
   ("set-current-module" . (set-current-module (resolve-module '(guile))))
   ("macro expansion hooks" . (macroexpand '(+ 1 2)))
   ("hash tables as state" . (make-hash-table))
   ("string ports" . (open-input-string "x"))))
(test-assert "allowed bindings still work" (reachable? '(string-upcase (string-append "o" "k"))))

(test-end "authority")
