(use-modules (srfi srfi-64) (srfi srfi-1) (ice-9 textual-ports)
             (live-agent diff) (live-agent changes) (live-agent sha256))

(test-begin "changes")

;; Unified diffs
(define modify (unified-diff "a\nb\nc\n" "a\nB\nc\nd\n" "a/x.txt" "b/x.txt"))
(test-assert "diff carries labels" (and (string-contains modify "--- a/x.txt")
                                         (string-contains modify "+++ b/x.txt")))
(test-equal "diffstat counts hunk lines only" '(2 . 1) (diffstat modify))
(test-equal "identical text yields an empty diff" "" (unified-diff "same\n" "same\n" "a/x" "b/x"))
(define create (unified-diff #f "new\n" "a/n.txt" "b/n.txt"))
(test-assert "create diffs from /dev/null" (string-contains create "--- /dev/null"))
(test-equal "create diffstat" '(1 . 0) (diffstat create))
(test-equal "diffstat formatting" "(+2 −1)" (format-diffstat '(2 . 1)))
(test-assert "content lines starting with dashes are counted, headers are not"
  (equal? '(1 . 1) (diffstat (unified-diff "--- x\n" "+++ y\n" "a/z" "b/z"))))
(define long (unified-diff "" (string-join (map number->string (iota 200)) "\n" 'suffix) "a/l" "b/l"))
(test-assert "preview truncates with a hint"
  (let ((preview (diff-preview long 20)))
    (and (string-contains preview "more lines")
         (< (length (string-split preview #\newline)) 25))))
(test-equal "short diffs preview unchanged" modify (diff-preview modify 100))

;; Ledger
(define root (string-append "/tmp/shift-changes-test-" (number->string (getpid))))
(system* "mkdir" "-p" root)
(define ledger (open-ledger root))
(define original "alpha\n")
(define updated "alpha\nbeta\n")

(test-assert "unseen files are never stale" (ledger-check-stale! ledger "a.txt" #f))
(ledger-observe! ledger 3 "a.txt" (sha256-string original))
(test-equal "observation records the turn" 3 (cdr (ledger-seen ledger "a.txt")))
(test-error "changed content after observation is stale" #t
  (ledger-check-stale! ledger "a.txt" (sha256-string "tampered\n")))
(test-assert "matching content is not stale"
  (ledger-check-stale! ledger "a.txt" (sha256-string original)))

(define seq (ledger-begin! ledger 4 "call_1" "edit" "a.txt" original updated))
(test-equal "begin stores the pre-image" original
  (ledger-read-blob ledger (sha256-string original)))
(test-equal "begin stores the post-image" updated
  (ledger-read-blob ledger (sha256-string updated)))
(test-equal "the started entry is open" seq (assq-ref (ledger-open-entry ledger) 'seq))
(test-equal "started entries are not turn changes" '() (ledger-turn-entries ledger 4))
(ledger-commit! ledger seq)
(test-assert "commit closes the entry" (not (ledger-open-entry ledger)))
(test-equal "commit updates last-seen to the post-image" (sha256-string updated)
  (car (ledger-seen ledger "a.txt")))
(test-equal "committed entry is a turn change" 1 (length (ledger-turn-entries ledger 4)))
(test-error "double commit is rejected" #t (ledger-commit! ledger seq))

(define created (ledger-begin! ledger 4 "call_2" "write" "b.txt" #f "fresh\n"))
(test-assert "creates record no pre-image" (not (assq-ref (ledger-open-entry ledger) 'before)))
(ledger-abort! ledger created)
(test-equal "aborted entries are not turn changes" 1 (length (ledger-turn-entries ledger 4)))

(define pending (ledger-begin! ledger 5 "call_3" "write" "c.txt" #f "half\n"))
(define reopened (open-ledger root))
(test-equal "replay restores entries" 3 (length (ledger-entries reopened)))
(test-equal "replay restores the open entry" pending (assq-ref (ledger-open-entry reopened) 'seq))
(test-equal "replay restores last-seen from commits" (sha256-string updated)
  (car (ledger-seen reopened "a.txt")))
(test-equal "replay continues the sequence" (+ pending 1)
  (ledger-begin! reopened 6 "call_4" "edit" "a.txt" updated original))

(let ((port (open-file (string-append root "/changes.jsonl") "a")))
  (display "{\"kind\":\"change\",\"seq\":" port)
  (close-port port))
(test-assert "a torn final line is skipped on replay" (ledger? (open-ledger root)))

;; Undo
(define project (string-append root "/project"))
(system* "mkdir" "-p" project)
(define (put! path text)
  (call-with-output-file (string-append project "/" path) (lambda (port) (display text port))))
(define (get path) (call-with-input-file (string-append project "/" path) get-string-all))
(define undo-ledger (open-ledger (string-append root "/undo-state")))
(define (mutate! turn tool path before after)
  (if after (put! path after) (delete-file (string-append project "/" path)))
  (ledger-commit! undo-ledger (ledger-begin! undo-ledger turn "c" tool path before after)))
(put! "x.txt" "x1\n")
(put! "gone.txt" "bye\n")
(mutate! 10 "edit" "x.txt" "x1\n" "x2\n")
(mutate! 10 "edit" "x.txt" "x2\n" "x3\n")
(mutate! 10 "write" "new.txt" #f "fresh\n")
(mutate! 10 "apply_patch" "gone.txt" "bye\n" #f)
(mutate! 11 "edit" "x.txt" "x3\n" "x4\n")

(test-equal "turn groups keep the earliest pre-image and latest post-image"
  (list "x.txt" (sha256-string "x1\n") (sha256-string "x3\n"))
  (car (ledger-turn-groups undo-ledger 10)))
(test-equal "undoable turns are newest first" '(11 10) (ledger-undoable-turns undo-ledger))
(put! "x.txt" "x4 plus user edit\n")
(test-error "undo refuses when a changed file diverged" #t (ledger-undo! undo-ledger project 11))
(test-equal "a refused undo touches nothing" "x4 plus user edit\n" (get "x.txt"))
(put! "x.txt" "x4\n")
(test-equal "undo restores the turn's files" '("x.txt") (map car (ledger-undo! undo-ledger project 11)))
(test-equal "the file is back to its pre-turn content" "x3\n" (get "x.txt"))
(test-equal "an undone turn leaves the stack" '(10) (ledger-undoable-turns undo-ledger))
(test-error "a turn cannot be undone twice" #t (ledger-undo! undo-ledger project 11))
(ledger-undo! undo-ledger project 10)
(test-assert "undoing a turn removes files it created and recreates files it deleted"
  (and (string=? "x1\n" (get "x.txt"))
       (not (file-exists? (string-append project "/new.txt")))
       (string=? "bye\n" (get "gone.txt"))))
(test-equal "undo updates last-seen to the restored images" (sha256-string "x1\n")
  (car (ledger-seen undo-ledger "x.txt")))
(test-equal "undone turns survive replay" '()
  (ledger-undoable-turns (open-ledger (string-append root "/undo-state"))))

;; Interrupted mutations
(define open-ledger* (open-ledger (string-append root "/open-state")))
(put! "u.txt" "u-before\n")
(put! "w.txt" "w-after\n")
(put! "d.txt" "d-strange\n")
(ledger-begin! open-ledger* 3 "c" "edit" "u.txt" "u-before\n" "u-after\n")
(ledger-begin! open-ledger* 3 "c" "edit" "w.txt" "w-before\n" "w-after\n")
(ledger-begin! open-ledger* 3 "c" "edit" "d.txt" "d-before\n" "d-after\n")
(test-equal "resolving open entries classifies each file"
  '(("u.txt" . unchanged) ("w.txt" . restored) ("d.txt" . diverged))
  (ledger-resolve-open! open-ledger* project))
(test-equal "a completed write is put back to its pre-image" "w-before\n" (get "w.txt"))
(test-equal "a diverged file is left alone" "d-strange\n" (get "d.txt"))
(test-equal "settled entries close; the diverged one stays open" '("d.txt")
  (map (lambda (entry) (assq-ref entry 'path)) (ledger-open-entries open-ledger*)))

(system* "rm" "-rf" root)
(test-end "changes")
