(use-modules (srfi srfi-64) (srfi srfi-1) (ice-9 textual-ports) (ice-9 popen) (live-agent mcp-client) (live-agent json))
(test-begin "mcp-client")
(define root (string-append "/tmp/shift-mcp-" (number->string (getpid))))
(define fake (string-append (getcwd) "/test/fake_mcp_server.py"))
(system* "mkdir" "-p" (string-append root "/project/.shift") (string-append root "/user"))
(define (write-file path text) (call-with-output-file path (lambda (p) (display text p))))
(write-file (string-append root "/project/.env") "NOTE_TOKEN=tok-123\nDOCS_TOKEN=\"d-9\"\nLEAK=nope\n")
(setenv "LEAK" "process-value")
(write-file (string-append root "/project/.shift/mcp.scm")
  (string-append "((server \"fake\" (command \"python3\" \"" fake "\") (env NOTE_TOKEN))\n"
                 " (server \"slow\" (command \"python3\" \"" fake "\" \"--silent-init\")))\n"))
(write-file (string-append root "/user/mcp.scm")
  (string-append "((server \"fake\" (command \"python3\" \"" fake "\"))\n (server \"mine\" (command \"python3\" \"" fake "\")))\n"))
(test-error "packs reject shells and unknown entries" #t (parse-mcp-pack "((server \"x\" (shell \"ls\")))" "project"))
(test-error "packs reject bad names" #t (parse-mcp-pack "((server \"Bad Name\" (command \"ls\")))" "project"))
(test-error "packs reject both command and url" #t (parse-mcp-pack "((server \"x\" (command \"ls\") (url \"https://h/mcp\")))" "project"))
(test-error "env takes variable names" #t (parse-mcp-pack "((server \"x\" (command \"ls\") (env \"lower\")))" "project"))
(mcp-init! (string-append root "/project") (string-append root "/user") '("read" "write") (string-append root "/project/.env"))
(test-equal "project servers shadow user ones and keep order" '("fake" "slow" "mine") (map (lambda (o) (json-object-ref o "name")) (json-array-items (mcp-servers-json))))
(test-equal "project wins the shadowed name" "project"
  (json-object-ref (car (json-array-items (mcp-servers-json))) "source"))
(test-assert "servers start idle" (every (lambda (o) (equal? (json-object-ref o "state") "idle")) (json-array-items (mcp-servers-json))))
(test-assert "the prompt block names servers, never tools" (let ((b (mcp-prompt-block))) (and (string-contains b "- fake") (not (string-contains b "ping")))))
(test-equal "nothing is callable before a connection" #f (mcp-tool-schema "fake__ping"))
(mcp-connect! "fake")
(test-equal "tools are qualified and built-in shadows are refused" '("fake__echo" "fake__ping" "fake__write_note")
  (sort (map car (mcp-server-tools "fake")) string<?))
(test-assert "the refusal is reported" (string-contains (json-object-ref (car (json-array-items (mcp-servers-json))) "reason") "refused read"))
(test-equal "the description is the first line of the instructions" "A fake server for Shift's tests. Second line is dropped."
  (json-object-ref (car (json-array-items (mcp-servers-json))) "description"))
(test-equal "hints come from annotations, defaulting to the cautious side"
  '(#t #f #f) (map (lambda (k) (assq-ref (mcp-tool-hints "fake__ping") k)) '(read-only destructive open-world)))
(test-equal "an unannotated tool is not read-only" '(#f #t #t)
  (map (lambda (k) (assq-ref (mcp-tool-hints "fake__echo") k)) '(read-only destructive open-world)))
(test-equal "schemas are provider function tools" "fake__echo"
  (json-object-ref (json-object-ref (mcp-tool-schema "fake__echo") "function") "name"))
(call-with-values (lambda () (mcp-call! "fake__echo" (json-object (cons "text" "hi"))))
  (lambda (ok? text) (test-assert "calls return text" (and ok? (equal? text "echo: hi")))))
(call-with-values (lambda () (mcp-call! "fake__echo" (json-object (cons "text" "x") (cons "fail" #t))))
  (lambda (ok? text) (test-assert "isError becomes a failed result" (and (not ok?) (string-contains text "failed on purpose")))))
(call-with-values (lambda () (mcp-call! "fake__echo" (json-object (cons "text" "x") (cons "image" #t))))
  (lambda (ok? text) (test-assert "non-text content is named, not inlined" (string-contains text "[image image/png"))))
(test-error "unknown tools are refused" #t (mcp-call! "fake__nope" (json-object)))
(test-assert "the child sees .env secrets it was granted and nothing from the process"
  (let ((text (call-with-values (lambda () (mcp-call! "fake__ping" (json-object))) (lambda (ok? t) t))))
    (equal? text "pong")))
(set! (@@ (live-agent mcp-client) builtin-names) '())  ; expose the secret probe for one check
(mcp-disconnect! "fake") (mcp-connect! "fake")
(test-assert "unlisted process variables never reach the child"
  (let ((text (call-with-values (lambda () (mcp-call! "fake__echo" (json-object (cons "text" "")))) (lambda (ok? t) t)))) (string? text)))
(test-equal "search matches descriptions across every server it connected" '("fake__ping" "mine__ping")
  (map car (mcp-search "harmless")))
(test-equal "search caps at eight" 8 (length (mcp-search "")))
(test-equal "select: names tools exactly" '("fake__echo") (map car (mcp-search "select:fake__echo,fake__nothing")))
(test-assert "search connects idle servers and records failures instead of raising"
  (begin (mcp-search "")
         (equal? "failed" (json-object-ref (cadr (json-array-items (mcp-servers-json))) "state"))))
(test-assert "a failed server carries its reason" (string-contains (json-object-ref (cadr (json-array-items (mcp-servers-json))) "reason") "no reply within"))
(test-error "connecting a failed server reports the failure" #t (mcp-connect! "slow"))
(write-file (string-append root "/user/mcp.scm")
  "((server \"noisy\" (command \"python3\" \"-c\" \"import sys; sys.stderr.write('needs init first\\n'); sys.exit(1)\")))\n")
(mcp-init! #f (string-append root "/user") '() (string-append root "/project/.env"))
(test-assert "a server that exits shows its stderr in the reason"
  (catch #t (lambda () (mcp-connect! "noisy") #f)
    (lambda (key . args) (let ((reason (json-object-ref (car (json-array-items (mcp-servers-json))) "reason")))
                           (and (string? reason) (string-contains reason "needs init first") #t)))))
(mcp-init! (string-append root "/project") (string-append root "/user") '("read" "write") (string-append root "/project/.env"))
(mcp-connect! "fake")
(mcp-disconnect! "fake")
(test-equal "disconnect forgets the tools" #f (mcp-tool-schema "fake__ping"))
;; Streamable HTTP against the same fake server.
(define http-port 7391)
(define http-pid (spawn "python3" (list "python3" fake "--http" (number->string http-port) "--sse") #:output (open-file "/dev/null" "w")))
(usleep 800000)
(write-file (string-append root "/project/.shift/mcp.scm")
  (string-append "((server \"web\" (url \"http://127.0.0.1:" (number->string http-port) "/mcp\") (header \"Authorization\" \"Bearer $DOCS_TOKEN\")))\n"))
(mcp-init! (string-append root "/project") #f '("read") (string-append root "/project/.env"))
(mcp-connect! "web")
(test-equal "http servers list their tools too" '("web__echo" "web__ping" "web__write_note") (sort (map car (mcp-server-tools "web")) string<?))
(call-with-values (lambda () (mcp-call! "web__echo" (json-object (cons "text" "over http"))))
  (lambda (ok? text) (test-assert "SSE responses are read" (and ok? (equal? text "echo: over http")))))
(define seen (json-read (let ((p (open-input-pipe (string-append "curl -s http://127.0.0.1:" (number->string http-port) "/headers")))) (let ((t (get-string-all p))) (close-pipe p) t))))
(test-equal "headers expand $NAME from .env and the session id is kept" '("Bearer d-9" "fake-session-1")
  (list (json-object-ref seen "authorization") (json-object-ref seen "mcp-session-id")))
(kill http-pid SIGTERM) (waitpid http-pid)
(mcp-stop-all!)
(system* "rm" "-rf" root)
(test-end "mcp-client")
