(use-modules (srfi srfi-64) (srfi srfi-1) (ice-9 textual-ports) (live-agent plugins) (live-agent json))
(test-begin "plugins")
(define root (string-append "/tmp/shift-plugins-" (number->string (getpid))))
(define (write-file path text)
  (system* "mkdir" "-p" (dirname path))
  (call-with-output-file path (lambda (p) (display text p))))
(write-file (string-append root "/install/plugins/demo/plugin.scm")
  "((plugin \"demo\" \"0.1\")\n (description \"A demo plugin\")\n (requires (command \"sh\"))\n (mcp (server \"demo\" (command \"python3\" \"fake.py\")))\n (skills \"skills\")\n (panes \"panes.scm\")\n (theme \"themes/demo.scm\")\n (agent \"agent/prompt.scm\")\n (allow-run (\"demo\" \"status\"))\n (allow-mcp \"demo__ping\")\n (env DEMO_TOKEN)\n (secret DEMO_SECRET (op \"op://Private/demo/token\")))\n")
(write-file (string-append root "/install/plugins/demo/skills/demo-skill/SKILL.md") "---\nname: demo-skill\ndescription: demo\n---\nbody\n")
(write-file (string-append root "/install/plugins/demo/panes.scm") "((pane \"demo\" \"DEMO\" (text \"hi\")))\n")
(write-file (string-append root "/install/plugins/demo/themes/demo.scm") "((accent . \"#ff0000\"))\n")
(write-file (string-append root "/install/plugins/demo/agent/prompt.scm") "(define agent-system-prompt \"demo prompt\")\n")
(write-file (string-append root "/install/plugins/broken/plugin.scm") "((plugin \"broken\" \"0.1\") (skills \"nope\"))\n")
(write-file (string-append root "/install/plugins/needs/plugin.scm") "((plugin \"needs\" \"0.1\") (requires (command \"no-such-command-xyz\")))\n")
(write-file (string-append root "/user/plugins/demo/plugin.scm") "((plugin \"demo\" \"0.2\") (description \"user copy wins\"))\n")
(write-file (string-append root "/project/.shift-plugin/plugin.scm") "((plugin \"self\" \"1.0\") (description \"the project's own plugin\"))\n")
(plugins-init! (string-append root "/install") (string-append root "/project") (string-append root "/user") '())
(test-equal "every folder with a manifest is indexed, later sources shadowing earlier ones by name"
  '("broken" "needs" "demo" "self") (map (lambda (p) (plugin-field p 'name)) (plugin-index)))
(test-equal "the user copy of demo shadows the bundled one" "0.2" (plugin-field (plugin-find "demo") 'version))
(test-equal "a repository's own .shift-plugin is found" "repository" (plugin-field (plugin-find "self") 'source))
(test-assert "a missing folder makes the plugin invalid with the reason"
  (and (not (plugin-field (plugin-find "broken") 'valid)) (string-contains (plugin-field (plugin-find "broken") 'error) "skills folder")))
(test-equal "a missing command is reported, not fatal" '("no-such-command-xyz") (plugin-field (plugin-find "needs") 'missing))
(test-assert "available means valid with every command present"
  (and (plugin-available? (plugin-find "self")) (not (plugin-available? (plugin-find "needs")))))
(plugins-init! (string-append root "/install") (string-append root "/project") #f '())
(define demo (plugin-find "demo"))
(test-equal "sections resolve to paths inside the plugin" (string-append root "/install/plugins/demo/skills") (plugin-field demo 'skills))
(test-equal "mcp forms are kept verbatim" '((server "demo" (command "python3" "fake.py"))) (plugin-field demo 'mcp))
(test-equal "allowlist proposals and secrets are parsed" '((("demo" "status")) ("demo__ping") (("DEMO_SECRET" . "op://Private/demo/token")) ("DEMO_TOKEN"))
  (list (plugin-field demo 'allow-run) (plugin-field demo 'allow-mcp) (plugin-field demo 'secrets) (plugin-field demo 'env)))
(test-error "manifests reject unknown sections" #t (parse-plugin-manifest "((plugin \"x\" \"1\") (python \"a.py\"))" "/tmp" "t"))
(test-error "manifests reject files outside the plugin" #t (parse-plugin-manifest "((plugin \"x\" \"1\") (skills \"../elsewhere\"))" "/tmp" "t"))
(test-error "manifests need the plugin header" #t (parse-plugin-manifest "((description \"x\"))" "/tmp" "t"))
(test-equal "check-plugin-dir returns the parsed plugin" "self" (plugin-field (check-plugin-dir (string-append root "/project/.shift-plugin")) 'name))
(test-error "check-plugin-dir raises for invalid manifests" #t (check-plugin-dir (string-append root "/install/plugins/broken")))
(test-assert "json carries the contribution summary and enabled state"
  (let ((o (car (filter (lambda (o) (equal? (json-object-ref o "name") "demo")) (json-array-items (plugins-json (lambda (n) #t)))))))
    (and (json-object-ref o "enabled") (member "skills" (json-array-items (json-object-ref o "contributes")))
         (member "1 mcp" (json-array-items (json-object-ref o "contributes"))))))
(system* "rm" "-rf" root)
(test-end "plugins")
