(use-modules (srfi srfi-64) (ice-9 textual-ports) (live-agent ui) (live-agent json))
(test-begin "ui")
(define root (string-append "/tmp/shift-ui-" (number->string (getpid))))
(system* "mkdir" "-p" (string-append root "/project/themes") (string-append root "/session"))
(setenv "SHIFT_INSTALL_ROOT" (getcwd))
(setenv "XDG_CONFIG_HOME" (string-append root "/config"))
(define (config) (json-object-ref (ui-state) "config"))
(define (patch . entries) (ui-action! (json-object (cons "action" "patch") (cons "patch" (apply json-object entries)))))
(ui-init! (string-append root "/project") (string-append root "/session"))
(test-equal "default theme" "acid" (json-object-ref (config) "theme"))
(test-equal "motion defaults on" #t (json-object-ref (config) "motion"))
(patch (cons "motion" #f))
(test-equal "motion can be disabled" #f (json-object-ref (config) "motion"))
(test-error "motion must be boolean" #t (patch (cons "motion" "off")))
(patch (cons "identity" "thrashr888") (cons "branding" "replace") (cons "placement" "left"))
(test-equal "personal identity" "thrashr888" (json-object-ref (config) "identity"))
(patch (cons "theme" "blueprint"))
(test-equal "placement survives theme change" "left" (json-object-ref (config) "placement"))
(test-equal "theme supplies its palette" 18 (json-object-ref (config) "background"))
(define before (json-write (ui-state)))
(test-error "authority is not a UI preference" #t (patch (cons "mode" "auto")))
(test-error "agent UI action cannot use host mode route" #t
  (ui-action! (json-object (cons "action" "session-command") (cons "command" "/mode auto"))))
(test-error "control characters rejected" #t (patch (cons "identity" "x\x1b;[2J")))
(test-error "fractional color representation rejected" #t (patch (cons "accent" 65.0)))
(test-error "theme path traversal rejected" #t (patch (cons "theme" "../bad")))
(test-equal "invalid patch leaves current UI untouched" before (json-write (ui-state)))
(ui-action! (json-object (cons "action" "undo")))
(test-equal "undo restores theme" "acid" (json-object-ref (config) "theme"))
(ui-stop!)
(ui-init! (string-append root "/project") (string-append root "/session"))
(test-equal "identity survives resume" "thrashr888" (json-object-ref (config) "identity"))
(test-equal "branding survives resume" "replace" (json-object-ref (config) "branding"))
(test-equal "motion preference survives resume" #f (json-object-ref (config) "motion"))
(ui-action! (json-object (cons "action" "save") (cons "scope" "user")))
(ui-stop!)
(ui-init! (string-append root "/other") #f)
(test-equal "explicit user save supplies other project defaults" "thrashr888" (json-object-ref (config) "identity"))
(ui-stop!)
(ui-init! (string-append root "/project") (string-append root "/session"))
(define pack (string-append root "/project/themes/custom.scm"))
(call-with-output-file pack (lambda (p) (display "((background . 22) (sections . (\"files\")))" p)))
(patch (cons "theme" "custom"))
(test-equal "theme list includes installed and project packs"
  '("acid" "apex" "afterhours" "paddock" "blueprint" "qdos" "custom")
  (json-array-items (json-object-ref (ui-state) "themes")))
(test-equal "custom Scheme data pack" 22 (json-object-ref (config) "background"))
(call-with-output-file pack (lambda (p) (display "(system \"touch never\")" p)))
(define good (json-write (ui-state)))
(test-error "executable theme is rejected" #t (ui-action! (json-object (cons "action" "reload"))))
(test-equal "failed reload keeps the working presentation" good (json-write (ui-state)))
(patch (cons "theme" "acid") (cons "background" 53))
(patch (cons "theme" "paddock"))
(test-equal "explicit colors survive new defaults and theme changes" 53 (json-object-ref (config) "background"))
(patch (cons "background" "#170626") (cons "theme" "afterhours"))
(test-equal "RGB colors are validated preferences" "#170626" (json-object-ref (config) "background"))
(test-equal "explicit placement still wins over Afterhours preset" "left" (json-object-ref (config) "placement"))
(patch (cons "theme" "apex"))
(test-equal "Apex preset is available" "apex" (json-object-ref (config) "theme"))
(test-error "short RGB rejected" #t (patch (cons "accent" "#abc")))
(test-error "nonhex RGB rejected" #t (patch (cons "accent" "#oops!!")))
(ui-stop!)
(system* "rm" "-rf" root)
(test-end "ui")
