(use-modules (srfi srfi-64) (ice-9 textual-ports) (live-agent ui) (live-agent json))
(test-begin "ui")
(define root (string-append "/tmp/shift-ui-" (number->string (getpid))))
(system* "mkdir" "-p" (string-append root "/project/themes") (string-append root "/session"))
(setenv "SHIFT_INSTALL_ROOT" (getcwd))
(setenv "XDG_CONFIG_HOME" (string-append root "/config"))
(define (config) (json-object-ref (ui-state) "config"))
(define (patch . entries) (ui-action! (json-object (cons "action" "patch") (cons "patch" (apply json-object entries)))))
(ui-init! (string-append root "/project") (string-append root "/session"))
(test-equal "default theme" "acid" (json-object-ref (config) "theme"))
(test-equal "motion defaults on" #t (json-object-ref (config) "motion"))
(patch (cons "motion" #f))
(test-equal "motion can be disabled" #f (json-object-ref (config) "motion"))
(test-error "motion must be boolean" #t (patch (cons "motion" "off")))
(patch (cons "identity" "thrashr888") (cons "branding" "replace") (cons "placement" "left"))
(test-equal "personal identity" "thrashr888" (json-object-ref (config) "identity"))
(patch (cons "theme" "blueprint"))
(test-equal "placement survives theme change" "left" (json-object-ref (config) "placement"))
(test-equal "theme supplies its palette" 18 (json-object-ref (config) "background"))
(define before (json-write (ui-state)))
(test-error "authority is not a UI preference" #t (patch (cons "mode" "auto")))
(test-error "agent UI action cannot use host mode route" #t
  (ui-action! (json-object (cons "action" "session-command") (cons "command" "/mode auto"))))
(test-error "control characters rejected" #t (patch (cons "identity" "x\x1b;[2J")))
(test-error "fractional color representation rejected" #t (patch (cons "accent" 65.0)))
(test-error "theme path traversal rejected" #t (patch (cons "theme" "../bad")))
(test-equal "invalid patch leaves current UI untouched" before (json-write (ui-state)))
(ui-action! (json-object (cons "action" "undo")))
(test-equal "undo restores theme" "acid" (json-object-ref (config) "theme"))
(ui-stop!)
(ui-init! (string-append root "/project") (string-append root "/session"))
(test-equal "identity survives resume" "thrashr888" (json-object-ref (config) "identity"))
(test-equal "branding survives resume" "replace" (json-object-ref (config) "branding"))
(test-equal "motion preference survives resume" #f (json-object-ref (config) "motion"))
(ui-action! (json-object (cons "action" "save") (cons "scope" "user")))
(ui-stop!)
(ui-init! (string-append root "/other") #f)
(test-equal "explicit user save supplies other project defaults" "thrashr888" (json-object-ref (config) "identity"))
(ui-stop!)
(ui-init! (string-append root "/project") (string-append root "/session"))
(define pack (string-append root "/project/themes/custom.scm"))
(call-with-output-file pack (lambda (p) (display "((background . 22) (sections . (\"files\")))" p)))
(patch (cons "theme" "custom"))
(test-equal "theme list includes installed and project packs"
  '("acid" "paddock" "blueprint" "qdos" "custom")
  (json-array-items (json-object-ref (ui-state) "themes")))
(test-equal "custom Scheme data pack" 22 (json-object-ref (config) "background"))
(call-with-output-file pack (lambda (p) (display "(system \"touch never\")" p)))
(define good (json-write (ui-state)))
(test-error "executable theme is rejected" #t (ui-action! (json-object (cons "action" "reload"))))
(test-equal "failed reload keeps the working presentation" good (json-write (ui-state)))
(patch (cons "theme" "acid") (cons "background" 53))
(patch (cons "theme" "paddock"))
(test-equal "explicit colors survive new defaults and theme changes" 53 (json-object-ref (config) "background"))
(patch (cons "background" "#170626") (cons "theme" "blueprint"))
(test-equal "RGB colors are validated preferences" "#170626" (json-object-ref (config) "background"))
(test-equal "explicit placement still wins over the Blueprint bottom preset" "left" (json-object-ref (config) "placement"))
(define pane (json-object (cons "name" "shift") (cons "title" "SHIFT")
  (cons "rows" (json-array (json-object (cons "text" "Checkout"))
                           (json-object (cons "field" "session.name"))
                           (json-object (cons "command" (json-array "git" "status" "--short")))))))
(patch (cons "panes" (json-array pane)))
(test-equal "user-owned panes are validated preferences" "shift"
  (json-object-ref (car (json-array-items (json-object-ref (config) "panes"))) "name"))
(test-error "pane names cannot shadow built-in tabs" #t
  (patch (cons "panes" (json-array (json-object (cons "name" "log") (cons "title" "L") (cons "rows" (json-array (json-object (cons "text" "x")))))))))
(test-error "pane rows accept only text, field or command" #t
  (patch (cons "panes" (json-array (json-object (cons "name" "x") (cons "title" "X") (cons "rows" (json-array (json-object (cons "python" "code")))))))))
(test-error "pane fields come from the known list" #t
  (patch (cons "panes" (json-array (json-object (cons "name" "x") (cons "title" "X") (cons "rows" (json-array (json-object (cons "field" "env.HOME")))))))))
(test-error "pane commands are argv lists" #t
  (patch (cons "panes" (json-array (json-object (cons "name" "x") (cons "title" "X") (cons "rows" (json-array (json-object (cons "command" "rm -rf /")))))))))
(call-with-output-file (string-append root "/project/panes.scm")
  (lambda (p) (display ";; project panes\n((pane \"proj\" \"PROJ\" (text \"from the project\") (field session.model) (command \"git\" \"status\")))" p)))
(patch (cons "panes" (json-array)))
(test-equal "a project's panes.scm loads when the session has no panes of its own" "proj"
  (json-object-ref (car (json-array-items (json-object-ref (config) "panes"))) "name"))
(test-equal "pane pack rows become the same JSON the preference validates"
  "{\"name\":\"proj\",\"title\":\"PROJ\",\"rows\":[{\"text\":\"from the project\"},{\"field\":\"session.model\"},{\"command\":[\"git\",\"status\"]}]}"
  (json-write (car (json-array-items (json-object-ref (config) "panes")))))
(test-equal "check-panes-file summarizes a valid pack" '(("proj" . 3)) (check-panes-file (string-append root "/project/panes.scm")))
(patch (cons "panes" (json-array pane)))
(test-equal "explicit panes win over the project file" "shift"
  (json-object-ref (car (json-array-items (json-object-ref (config) "panes"))) "name"))
(patch (cons "panes" (json-array)))
(call-with-output-file (string-append root "/project/panes.scm") (lambda (p) (display "((pane \"log\" \"L\" (text \"x\")))" p)))
(test-error "an invalid project panes.scm is rejected, not loaded" #t (ui-action! (json-object (cons "action" "reload"))))
(test-error "pane packs are data: no evaluation, no unknown rows" #t (panes-pack->json "((pane \"x\" \"X\" (eval (system \"true\"))))"))
(test-error "field names are symbols from the known list" #t (panes-pack->json "((pane \"x\" \"X\" (field env.HOME)))"))
(test-error "a pane pack is one form" #t (panes-pack->json "((pane \"x\" \"X\" (text \"a\"))) (pane \"y\" \"Y\" (text \"b\"))"))
(delete-file (string-append root "/project/panes.scm"))
(patch (cons "mouse" #f))
(test-equal "mouse capture is a boolean preference" #f (json-object-ref (config) "mouse"))
(test-error "mouse capture must be boolean" #t (patch (cons "mouse" "off")))
(patch (cons "mouse" #t))
(patch (cons "terminal_colors" #t))
(test-equal "terminal color sync is a boolean preference" #t (json-object-ref (config) "terminal_colors"))
(test-error "terminal color sync must be boolean" #t (patch (cons "terminal_colors" "yes")))
(test-error "short RGB rejected" #t (patch (cons "accent" "#abc")))
(test-error "nonhex RGB rejected" #t (patch (cons "accent" "#oops!!")))
(ui-stop!)
(system* "rm" "-rf" root)
(test-end "ui")
