(use-modules (srfi srfi-64) (srfi srfi-1) (ice-9 textual-ports)
             (live-agent json) (live-agent workflow))
(test-begin "workflow")
(define project (let ((p (mkdtemp "/tmp/shift-workflow-XXXXXX"))) p))
(define (mkdirs path) (unless (file-exists? path) (mkdirs (dirname path)) (mkdir path)))
(define (write-workflow name text)
  (mkdirs (string-append project "/.shift/workflows/" name))
  (call-with-output-file (workflow-file project name) (lambda (p) (display text p))))

(test-equal "no workflows yet" '() (workflow-names project))
(write-workflow "release-check"
  "((workflow \"release-check\" 3)
    (description \"Verify a checkout before tagging\")
    (budget (rounds 20))
    (step \"status\" \"Run git status and report.\" (check (run \"true\")) (check (contains \"clean\")))
    (step \"notes\" \"Write the notes.\" (check (notes \"release.md\")) (check (file \"README.md\")) (check (judge \"the notes cover five commits\"))))")
(test-equal "the workflow is listed" '("release-check") (workflow-names project))
(define w (workflow-read project "release-check"))
(test-equal "name, version, budget" '("release-check" 3 20) (list (workflow-name w) (workflow-version w) (workflow-budget w)))
(test-equal "description" "Verify a checkout before tagging" (workflow-description w))
(test-equal "steps in order" '("status" "notes") (map step-name (workflow-steps w)))
(test-equal "checks parse to kinds" '(run contains) (map check-kind (step-checks (car (workflow-steps w)))))
(test-equal "a run check keeps its argv" '(run ("true")) (car (step-checks (car (workflow-steps w)))))
(test-equal "check text for display" "the notes cover five commits" (check-text (caddr (step-checks (cadr (workflow-steps w))))))

(define (error-message thunk)
  (catch #t (lambda () (thunk) #f) (lambda (key . args) (caught-message key args))))
(write-workflow "bad-head" "((workflow \"other\" 1) (step \"a\" \"do\"))")
(test-assert "the head must name the folder" (string-contains (error-message (lambda () (workflow-read project "bad-head"))) "must start with"))
(write-workflow "no-steps" "((workflow \"no-steps\" 1) (description \"x\"))")
(test-assert "a workflow needs a step" (string-contains (error-message (lambda () (workflow-read project "no-steps"))) "at least one step"))
(write-workflow "bad-check" "((workflow \"bad-check\" 1) (step \"a\" \"do\" (check (explode))))")
(test-assert "unknown checks are refused" (string-contains (error-message (lambda () (workflow-read project "bad-check"))) "unknown check"))
(write-workflow "dup" "((workflow \"dup\" 1) (step \"a\" \"do\") (step \"a\" \"again\"))")
(test-assert "step names are distinct" (string-contains (error-message (lambda () (workflow-read project "dup"))) "distinct"))
(write-workflow "code" "((workflow \"code\" 1) (step \"a\" \"do\")) (display \"never\")")
(test-assert "one data form only" (string-contains (error-message (lambda () (workflow-read project "code"))) "one data form"))
(test-assert "bad names are refused before the disk is touched"
  (string-contains (error-message (lambda () (workflow-read project "../etc"))) "lowercase"))
(test-equal "unreadable workflows are listed with their error"
  #t (let ((s (workflow-summary project "bad-head"))) (and (string-contains (json-object-ref s "error") "must start with") #t)))

;; Checks against a fake runner, notes and judge.
(define ran '())
(define context
  `((answer . "The tree is clean.") (root . ,project)
    (run . ,(lambda (argv) (set! ran (cons argv ran)) (if (equal? argv '("true")) (cons 0 "") (cons 1 "boom"))))
    (notes-exists? . ,(lambda (name) (string=? name "release.md")))
    (task . "Report on the tree.")
    (judge . ,(lambda (criterion answer task) `((holds . ,(and (string-contains answer "clean") (equal? task "Report on the tree."))) (confidence . 0.91) (model . "typesafe/jev-1.13.0"))))))
(define (result check) (evaluate-check check context))
(test-equal "a run check passes on exit 0" #t (assq-ref (result '(run ("true"))) 'ok))
(test-equal "a run check fails on exit 1 and says so" '(#f "exit 1")
  (let ((r (result '(run ("false"))))) (list (assq-ref r 'ok) (assq-ref r 'detail))))
(test-equal "contains looks at the answer" '(#t #f) (list (assq-ref (result '(contains "clean")) 'ok) (assq-ref (result '(contains "dirty")) 'ok)))
(test-equal "file is project-relative" '(#t #f)
  (begin (call-with-output-file (string-append project "/README.md") (lambda (p) (display "x" p)))
         (list (assq-ref (result '(file "README.md")) 'ok) (assq-ref (result '(file "nope.md")) 'ok))))
(test-equal "notes asks the session" '(#t #f) (list (assq-ref (result '(notes "release.md")) 'ok) (assq-ref (result '(notes "plan.md")) 'ok)))
(let ((r (result '(judge "the tree is clean"))))
  (test-equal "a judge check carries confidence and model" '(#t 0.91 "typesafe/jev-1.13.0")
    (list (assq-ref r 'ok) (assq-ref r 'confidence) (assq-ref r 'model))))
(test-equal "a fallback verdict says what the typed judge could not do" "holds (confidence 0.70) · after the typed judge failed (auth): HTTP 401"
  (assq-ref (evaluate-check '(judge "x") (cons (cons 'judge (lambda (c a t) '((holds . #t) (confidence . 0.7) (fallback . "the typed judge failed (auth): HTTP 401")))) (alist-delete 'judge context))) 'detail))
(test-equal "no judge means the check fails, never passes" '(#f "no judge could answer")
  (let ((r (evaluate-check '(judge "anything") (cons '(judge . #f) (alist-delete 'judge context)))))
    (list (assq-ref r 'ok) (assq-ref r 'detail))))
(test-equal "a judge that names its failure is quoted" "Jev is off for this session"
  (assq-ref (evaluate-check '(judge "x") (cons (cons 'judge (lambda (c a t) '((reason . "Jev is off for this session")))) (alist-delete 'judge context))) 'detail))
(test-equal "a check that raises is a failed check" #f
  (assq-ref (evaluate-check '(run ("x")) (cons (cons 'run (lambda (argv) (error "no runner"))) (alist-delete 'run context))) 'ok))

;; Run records.
(define record
  `((workflow . "release-check") (version . 3) (session . "default") (started . "2026-09-21T20:00:00Z")
    (status . failed) (rounds . 7) (error . #f)
    (steps . (((name . "status") (status . ok) (rounds . 3) (checks . (((kind . run) (text . "true") (ok . #t) (detail . "exit 0")))))
              ((name . "notes") (status . failed) (rounds . 4)
               (checks . (((kind . judge) (text . "the notes cover five commits") (ok . #f) (detail . "does not hold (confidence 0.80)") (confidence . 0.8) (model . "typesafe/jev-1.13.0")))))))))
(define path1 (workflow-record-run! project "release-check" record))
(test-assert "runs are numbered from 1" (string-suffix? "/runs/1.json" path1))
(test-assert "the second run is 2" (string-suffix? "/runs/2.json" (workflow-record-run! project "release-check" (cons '(status . resolved) record))))
(test-equal "newest run first" "resolved" (json-object-ref (workflow-last-run project "release-check") "status"))
(test-equal "the record round-trips its checks"
  '("judge" #f 0.8)
  (let* ((run (cadr (workflow-runs project "release-check")))
         (check (car (json-array-items (json-object-ref (cadr (json-array-items (json-object-ref run "steps"))) "checks")))))
    (list (json-object-ref check "kind") (json-object-ref check "ok") (json-object-ref check "confidence"))))
(let ((s (workflow-summary project "release-check")))
  (test-equal "the summary carries steps, runs and the last run" '(3 ("status" "notes") 2 "resolved")
    (list (json-object-ref s "version") (json-array-items (json-object-ref s "steps")) (json-object-ref s "runs")
          (json-object-ref (json-object-ref s "last") "status"))))
(test-equal "workflows-json lists every folder" 6 (length (json-array-items (workflows-json project))))

;; Sources: the project first, then the user's folder, then plugins.
(define user-dir (string-append project "/user-workflows"))
(define plugin-dir (string-append project "/plugin/workflows"))
(define (write-source dir name text)
  (mkdirs (string-append dir "/" name))
  (call-with-output-file (string-append dir "/" name "/workflow.scm") (lambda (p) (display text p))))
(write-source user-dir "nightly" "((workflow \"nightly\" 1) (description \"From the user folder\") (step \"a\" \"do\"))")
(write-source plugin-dir "nightly" "((workflow \"nightly\" 9) (description \"From a plugin\") (step \"a\" \"do\"))")
(write-source plugin-dir "callers" "((workflow \"callers\" 1) (description \"Map callers\") (step \"a\" \"do\"))")
(write-source plugin-dir "release-check" "((workflow \"release-check\" 99) (step \"a\" \"shadowed\"))")
(workflows-init! project (list (cons "user" user-dir) (cons "plugin:demo" plugin-dir)))
(test-equal "names are the union of every source" #t
  (and (member "nightly" (workflow-names project)) (member "callers" (workflow-names project)) #t))
(test-equal "the project defines a name every other source has" '("project" 3)
  (let ((w (workflow-read project "release-check"))) (list (workflow-source w) (workflow-version w))))
(test-equal "the user folder beats a plugin" '("user" 1 "From the user folder")
  (let ((w (workflow-read project "nightly"))) (list (workflow-source w) (workflow-version w) (workflow-description w))))
(test-equal "a plugin's workflow reads with its label" "plugin:demo" (workflow-source (workflow-read project "callers")))
(test-equal "locate names the defining file" (string-append plugin-dir "/callers/workflow.scm") (cdr (workflow-locate "callers" project)))
(test-assert "a run of a plugin workflow lands in the project folder"
  (string-prefix? (string-append project "/.shift/workflows/callers/runs/")
                  (workflow-record-run! project "callers" '((workflow . "callers") (version . 1) (session . "s") (started . "t") (status . resolved) (rounds . 1) (error . #f) (steps . ())))))
(test-equal "summaries carry the source" "plugin:demo" (json-object-ref (workflow-summary project "callers") "source"))
(define before (workflows-signature))
(write-source plugin-dir "another" "((workflow \"another\" 1) (step \"a\" \"do\"))")
(test-assert "adding a workflow changes the signature" (not (equal? before (workflows-signature))))
(test-equal "and the signature settles" (workflows-signature) (workflows-signature))
(test-end "workflow")
