(define-module (shift mcp)
  #:use-module (ice-9 format)
  #:use-module (ice-9 threads)
  #:use-module (ice-9 textual-ports)
  #:use-module (rnrs bytevectors)
  #:use-module (ice-9 binary-ports)
  #:use-module (web request)
  #:use-module (web response)
  #:use-module (web uri)
  #:use-module (live-agent json)
  #:export (start-mcp! mcp-dispatch))

(define protocol-version "2025-11-25")
(define (tool name description properties required)
  (json-object (cons "name" name) (cons "description" description)
    (cons "inputSchema" (json-object (cons "type" "object") (cons "properties" properties)
                                    (cons "required" required) (cons "additionalProperties" #f)))))
(define tools
  (json-array
    (tool "shift_cancel" "Cancel the active turn while preserving its prior checkpoint." (json-object) (json-array))
    (tool "shift_status" "Inspect this live Shift process, project, model, settings and session." (json-object) (json-array))
    (tool "shift_prompt" "Submit a prompt to the live session. Uses the session's tool approval policy; busy sessions reject concurrent turns."
      (json-object (cons "text" (json-object (cons "type" "string")))) (json-array "text"))
    (tool "shift_inspect" "Inspect live state using /show, /settings, /context, /session, /generations, /receipt, /traces or /trace ID."
      (json-object (cons "command" (json-object (cons "type" "string")))) (json-array "command"))))
(define (peer-note dispatch value)
  (catch #t (lambda () (dispatch 'peer value)) (lambda _ #f)))
(define* (mcp-dispatch request dispatch #:optional (peer "anonymous"))
  (let ((id (json-object-ref request "id" #f))
        (method (json-object-ref request "method" ""))
        (params (json-object-ref request "params" (json-object))))
    (define (response value) (json-object (cons "jsonrpc" "2.0") (cons "id" id) (cons "result" value)))
    (catch #t
      (lambda ()
        (cond
          ((not id) #f)
          ((string=? method "initialize")
           (let ((info (json-object-ref params "clientInfo" (json-object))))
             (peer-note dispatch (json-object (cons "event" "connected") (cons "id" peer)
               (cons "name" (let ((name (json-object-ref info "name" "client"))) (if (string? name) name "client")))
               (cons "version" (let ((version (json-object-ref info "version" ""))) (if (string? version) version ""))))))
           (response (json-object (cons "protocolVersion" protocol-version)
             (cons "capabilities" (json-object (cons "tools" (json-object))))
             (cons "serverInfo" (json-object (cons "name" "shift") (cons "version" "0.1.0"))))))
          ((string=? method "ping") (response (json-object)))
          ((string=? method "tools/list") (response (json-object (cons "tools" tools))))
          ((string=? method "tools/call")
           (let* ((name (json-object-ref params "name"))
                  (arguments (json-object-ref params "arguments" (json-object)))
                  (result (cond
                    ((string=? name "shift_cancel") (dispatch 'cancel #f))
                    ((string=? name "shift_status") (dispatch 'status #f))
                    ((string=? name "shift_prompt") (dispatch 'prompt (json-object-ref arguments "text")))
                    ((string=? name "shift_inspect") (dispatch 'inspect (json-object-ref arguments "command")))
                    (else (error "unknown tool" name)))))
             (peer-note dispatch (json-object (cons "event" "call") (cons "id" peer) (cons "tool" name) (cons "ok" #t)
               (cons "summary" (let ((text (json-object-ref arguments "text" (json-object-ref arguments "command" ""))))
                                 (if (string? text) (if (> (string-length text) 80) (substring text 0 80) text) "")))))
             (response (json-object (cons "isError" #f)
               (cons "content" (json-array (json-object (cons "type" "text")
                 (cons "text" (if (string? result) result (json-write result))))))))))
          (else (error "unsupported method" method))))
      (lambda (key . args)
        (when (string=? method "tools/call")
          (peer-note dispatch (json-object (cons "event" "call") (cons "id" peer)
            (cons "tool" (let ((name (json-object-ref params "name" ""))) (if (string? name) name "")))
            (cons "ok" #f) (cons "summary" (format #f "~a" key)))))
        (if (string=? method "tools/call")
          (response (json-object (cons "isError" #t) (cons "content" (json-array
            (json-object (cons "type" "text") (cons "text" (format #f "~a: ~s" key args)))))))
          (json-object (cons "jsonrpc" "2.0") (cons "id" id)
            (cons "error" (json-object (cons "code" -32601) (cons "message" "Unsupported or invalid request")))))))))

(define (start-mcp! port-number dispatch)
  (let ((listener (socket PF_INET SOCK_STREAM 0)) (running? #t) (clients '()) (lock (make-mutex)))
    (setsockopt listener SOL_SOCKET SO_REUSEADDR 1)
    (bind listener AF_INET INADDR_LOOPBACK port-number)
    (listen listener 16)
    (sigaction SIGPIPE SIG_IGN)
    (define (respond client code value . extra)
      (let ((body (if value (string->utf8 (json-write value)) (make-bytevector 0))))
        (write-response (build-response #:code code #:headers
          (append `((content-type . (application/json)) (content-length . ,(bytevector-length body))
                    (connection . (close))) extra)) client)
        (put-bytevector client body) (force-output client)))
    (define (fresh-peer-id)
      (let ((port (open-input-file "/dev/urandom")))
        (let ((bytes (get-bytevector-n port 8)))
          (close-port port)
          (string-concatenate (map (lambda (i) (format #f "~2,'0x" (bytevector-u8-ref bytes i))) (iota 8))))))
    (define (serve client)
      (dynamic-wind
        (lambda () #t)
        (lambda ()
          (catch #t
            (lambda ()
              (let* ((request (read-request client))
                     (headers (request-headers request))
                     (host (assq-ref headers 'host))
                     (origin (assq-ref headers 'origin))
                     (length* (or (assq-ref headers 'content-length) 0))
                     (expected-token (getenv "SHIFT_MCP_TOKEN"))
                     ;; Drain bounded bodies even when rejecting headers, so
                     ;; closing the socket does not replace our HTTP error with RST.
                     (body (and (<= length* 1048576) (not (assq-ref headers 'transfer-encoding))
                                (read-request-body request))))
                (cond
                  ((or (not host) (not (member (car host) '("127.0.0.1" "localhost")))
                       (and origin (not (member origin
                         (list (format #f "http://127.0.0.1:~a" port-number)
                               (format #f "http://localhost:~a" port-number))))))
                   (respond client 403 #f))
                  ((and expected-token
                        (not (equal? (assq-ref headers 'authorization) (string-append "Bearer " expected-token))))
                   (respond client 401 #f))
                  ((not (string=? (uri-path (request-uri request)) "/mcp")) (respond client 404 #f))
                  ((not (eq? (request-method request) 'POST)) (respond client 405 #f))
                  ((or (> length* 1048576) (assq-ref headers 'transfer-encoding)) (respond client 413 #f))
                  (else
                    ;; Peers keep the Mcp-Session-Id an initialize answered with;
                    ;; the session shows who is attached and what they called.
                    (let* ((request (json-read (utf8->string body)))
                           (initialize? (equal? (json-object-ref request "method" "") "initialize"))
                           (given (assq-ref headers 'mcp-session-id))
                           (peer (cond (initialize? (fresh-peer-id))
                                       ((string? given) (if (> (string-length given) 64) "anonymous" given))
                                       (else "anonymous")))
                           (response (mcp-dispatch request dispatch peer)))
                      (if initialize?
                          (respond client (if response 200 202) response (cons 'mcp-session-id peer))
                          (respond client (if response 200 202) response)))))))
            (lambda _ (catch #t (lambda () (respond client 400 #f)) (lambda _ #f)))))
        (lambda ()
          (unless (port-closed? client) (close-port client))
          (with-mutex lock (set! clients (delq client clients))))))
    (let ((thread
           (call-with-new-thread
             (lambda ()
               (let loop ()
                 (when running?
                   (catch #t
                     (lambda ()
                       (let ((client (car (accept listener))))
                         (setsockopt client SOL_SOCKET SO_RCVTIMEO '(5 . 0))
                         (with-mutex lock (set! clients (cons client clients)))
                         (call-with-new-thread (lambda () (serve client)))))
                     (lambda _ #f))
                   (loop)))))))
      (lambda ()
        (set! running? #f)
        ;; Waking accept is portable; shutdown on a listening socket raises
        ;; ENOTCONN on macOS and closing from another thread need not wake it.
        (let ((wake (socket PF_INET SOCK_STREAM 0)))
          (connect wake AF_INET INADDR_LOOPBACK port-number)
          (close-port wake))
        (with-mutex lock
          (for-each (lambda (client) (catch #t (lambda () (shutdown client 2)) (lambda _ #f))) clients))
        (join-thread thread)
        (close-port listener)))))
