(define-module (live-agent input)
  #:use-module (ice-9 readline)
  #:use-module (ice-9 textual-ports)
  #:use-module (srfi srfi-1)
  #:use-module (live-agent json)
  #:export (input-init! input-remember! input-history))
(define history-path #f)
(define (history-items port)
  (seek port 0 SEEK_SET)
  (let loop ((items '()) (line (get-line port)))
    (if (eof-object? line) (reverse items)
        (loop (cons (json-read line) items) (get-line port)))))
(define (recent items) (drop items (max 0 (- (length items) 500))))
(define (input-history)
  (if (and history-path (file-exists? history-path))
      (call-with-input-file history-path
        (lambda (port)
          (flock port LOCK_SH)
          (recent (history-items port))))
      '()))
(define (input-init! state)
  (set! history-path (string-append state "/input-history.jsonl"))
  (clear-history)
  (for-each add-history (input-history)))
(define (input-remember! line)
  (when (and (string? line) (not (string-null? (string-trim-both line))))
    (add-history line)
    (when history-path
      (let ((port (open-file history-path "a+")))
        (dynamic-wind
          (lambda () (chmod history-path #o600) (flock port LOCK_EX))
          (lambda ()
            (let* ((items (history-items port))
                   (next (recent (if (and (pair? items) (string=? (last items) line))
                                     items (append items (list line))))))
              (truncate-file port 0) (seek port 0 SEEK_SET)
              (for-each (lambda (item) (display (json-write item) port) (newline port)) next)
              (force-output port)))
          (lambda () (close-port port)))))))
