;; MCP client: external servers declared as data in .shift/mcp.scm (project)
;; and ~/.config/shift/mcp.scm (user), connected lazily, their tools offered
;; to the model as SERVER__TOOL under the process-owned policy. Secrets come
;; only from the session's .env; nothing in the file is evaluated.
(define-module (live-agent mcp-client)
  #:use-module (ice-9 textual-ports)
  #:use-module (ice-9 threads)
  #:use-module (ice-9 popen)
  #:use-module (live-agent redact)
  #:use-module (ice-9 format)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-14)
  #:use-module (srfi srfi-9)
  #:use-module (live-agent json)
  #:use-module ((live-agent tools) #:select (bounded))
  #:use-module (live-agent search)
  #:export (mcp-init! mcp-servers mcp-servers-json mcp-connect! mcp-disconnect! mcp-stop-all!
            mcp-tools mcp-tool-schema mcp-tool-hints mcp-tool-name? mcp-tool-server mcp-search mcp-call!
            mcp-prompt-block check-mcp-file parse-mcp-pack mcp-server-tools
            mcp-register! mcp-unregister! secret-sources!))

(define protocol-version "2025-11-25")
(define max-servers 8)
(define max-file-bytes 32768)
(define max-output (* 64 1024))
(define connect-timeout 10)
(define call-timeout 60)
(define search-limit 8)

(define-record-type <server>
  (%make-server name source transport argv url env-names headers)
  server?
  (name server-name) (source server-source) (transport server-transport)
  (argv server-argv) (url server-url) (env-names server-env-names) (headers server-headers)
  (state server-state set-server-state!)          ; idle connected failed
  (reason server-reason set-server-reason!)
  (description server-description set-server-description!)
  (tools server-tools set-server-tools!)          ; ((qualified schema hints) ...)
  (session-id server-session-id set-server-session-id!)
  (pid server-pid set-server-pid!)
  (in server-in set-server-in!) (out server-out set-server-out!)
  (next-id server-next-id set-server-next-id!)
  (lock server-lock set-server-lock!)
  (stderr-path server-stderr-path set-server-stderr-path!))
(define (make-server name source transport argv url env-names headers)
  (let ((s (%make-server name source transport argv url env-names headers)))
    (set-server-state! s 'idle) (set-server-reason! s #f) (set-server-description! s "")
    (set-server-tools! s '()) (set-server-session-id! s #f) (set-server-pid! s #f)
    (set-server-in! s #f) (set-server-out! s #f) (set-server-next-id! s 0)
    (set-server-lock! s (make-mutex)) (set-server-stderr-path! s #f)
    s))

(define servers '())
(define builtin-names '())
(define dotenv-path #f)
(define sources '())

;; --- the pack -------------------------------------------------------------
(define (valid-name? name)
  (and (string? name) (<= 1 (string-length name) 16)
       (string-every (lambda (c) (or (char-lower-case? c) (char-numeric? c) (char=? c #\-))) name)))
(define (env-name? value)
  (and (symbol? value)
       (string-every (lambda (c) (or (char-upper-case? c) (char-numeric? c) (char=? c #\_))) (symbol->string value))))
(define (server-form->record form source)
  (unless (and (list? form) (>= (length form) 3) (eq? (car form) 'server) (valid-name? (cadr form)))
    (error "servers are (server \"name\" (command ...)|(url ...) [(env NAME ...)] [(header KEY VALUE)] ...)" form))
  (let loop ((rest (cddr form)) (argv #f) (url #f) (env '()) (headers '()))
    (if (null? rest)
        (begin
          (unless (or argv url) (error "a server needs (command ...) or (url ...)" (cadr form)))
          (when (and argv url) (error "a server takes command or url, not both" (cadr form)))
          (make-server (cadr form) source (if argv 'stdio 'http) argv url env (reverse headers)))
        (let ((entry (car rest)))
          (unless (and (pair? entry) (symbol? (car entry)) (list? (cdr entry)))
            (error "server entries are (command ...), (url ...), (env ...) or (header ...)" entry))
          (case (car entry)
            ((command)
             (unless (and (pair? (cdr entry)) (<= (length (cdr entry)) 32) (every string? (cdr entry)))
               (error "command takes 1-32 argv strings" entry))
             (loop (cdr rest) (cdr entry) url env headers))
            ((url)
             (unless (and (= (length entry) 2) (string? (cadr entry))
                          (or (string-prefix? "https://" (cadr entry)) (string-prefix? "http://" (cadr entry))))
               (error "url takes one http(s) URL" entry))
             (loop (cdr rest) argv (cadr entry) env headers))
            ((env)
             (unless (every env-name? (cdr entry)) (error "env takes variable names like GITHUB_TOKEN" entry))
             (loop (cdr rest) argv url (append env (map symbol->string (cdr entry))) headers))
            ((header)
             (unless (and (= (length entry) 3) (string? (cadr entry)) (string? (caddr entry))
                          (not (string-index (cadr entry) #\newline)) (not (string-index (caddr entry) #\newline)))
               (error "header takes a key and a value" entry))
             (loop (cdr rest) argv url env (cons (cons (cadr entry) (caddr entry)) headers)))
            (else (error "unknown server entry" entry)))))))
(define (parse-mcp-pack text source)
  (let ((data (call-with-input-string text
                (lambda (p) (let ((form (read p)))
                  (unless (eof-object? (read p)) (error "an MCP pack is one list of server forms")) form)))))
    (unless (list? data) (error "an MCP pack is a list of (server ...) forms"))
    (let ((records (map (lambda (form) (server-form->record form source)) data)))
      (when (> (length records) max-servers) (error "at most 8 servers per pack"))
      (unless (= (length records) (length (delete-duplicates (map server-name records))))
        (error "server names must be unique"))
      records)))
(define (read-pack path source)
  (if (file-exists? path)
      (begin
        (when (> (stat:size (stat path)) max-file-bytes) (error "MCP pack exceeds 32 KiB" path))
        (parse-mcp-pack (call-with-input-file path get-string-all #:encoding "UTF-8") source))
      '()))
(define* (check-mcp-file #:optional (path ".shift/mcp.scm"))
  (unless (file-exists? path) (error "no such file" path))
  (map (lambda (s) (list (server-name s) (symbol->string (server-transport s)) (or (server-url s) (string-join (server-argv s) " "))))
       (read-pack path "project")))

;; (mcp-init! project-dir user-dir builtins dotenv) reads both packs; a
;; project server shadows a user server of the same name. Errors in a pack
;; are kept as a failed placeholder so the session still starts.
(define (mcp-init! project-dir user-dir builtins dotenv)
  (mcp-stop-all!)
  (set! builtin-names builtins) (set! dotenv-path dotenv)
  (set! sources (list (cons "project" (and project-dir (string-append project-dir "/.shift/mcp.scm")))
                      (cons "user" (and user-dir (string-append user-dir "/mcp.scm")))))
  (set! servers
    (let loop ((entries sources) (seen '()) (result '()))
      (if (null? entries)
          (reverse result)
          (let* ((source (caar entries)) (path (cdar entries))
                 (records (catch #t (lambda () (if path (read-pack path source) '()))
                            (lambda (key . args)
                              (let ((broken (make-server "pack" source 'stdio '("false") #f '() '())))
                                (set-server-state! broken 'failed)
                                (set-server-reason! broken (format #f "~a: ~a" path (error-text key args)))
                                (list broken)))))
                 (fresh (filter (lambda (s) (not (member (server-name s) seen))) records)))
            (loop (cdr entries) (append (map server-name fresh) seen) (append (reverse fresh) result)))))))
(define (error-text key args)
  (cond ((and (>= (length args) 2) (string? (cadr args)))
         (if (and (>= (length args) 3) (pair? (caddr args)))
             (format #f "~a ~s" (cadr args) (car (caddr args)))
             (cadr args)))
        (else (format #f "~a" key))))

;; Plugins add server forms under a source label and remove them by it.
(define (mcp-register! forms source)
  (for-each (lambda (form)
              (let ((record (server-form->record form source)))
                (unless (find-server (server-name record))
                  (set! servers (append servers (list record))))))
            forms))
(define (mcp-unregister! source)
  (for-each (lambda (s) (when (string=? (server-source s) source) (catch #t (lambda () (stdio-stop! s)) (lambda _ #f))))
            servers)
  (set! servers (filter (lambda (s) (not (string=? (server-source s) source))) servers)))
;; Secret sources: ((NAME . "op://vault/item/field") ...) resolved through the
;; op CLI when a server first needs them, cached for the process, never written.
(define secrets '())
(define secret-cache '())
(define (secret-sources! alist) (set! secrets alist))
(define (resolve-secret ref)
  (or (assoc-ref secret-cache ref)
      (let* ((port (open-pipe* OPEN_READ "op" "read" "--no-newline" ref))
             (value (get-string-all port))
             (status (close-pipe port)))
        (if (and (eqv? 0 (status:exit-val status)) (not (string-null? value)))
            (begin (register-secret! (let ((parts (string-split ref #\/))) (last parts)) value)
                   (set! secret-cache (acons ref value secret-cache)) value)
            #f))))
(define (resolved-secrets)
  (filter-map (lambda (s) (let ((v (catch #t (lambda () (resolve-secret (cdr s))) (lambda _ #f)))) (and v (cons (car s) v)))) secrets))
(define (mcp-servers) servers)
(define (find-server name) (find (lambda (s) (string=? (server-name s) name)) servers))

;; --- secrets: the session's .env only ---------------------------------------
(define (dotenv-entries)
  (append (if (and dotenv-path (file-exists? dotenv-path))
              ((@ (live-agent settings) read-dotenv) dotenv-path)
              '())
          (if (null? secrets) '() (resolved-secrets))))
(define (expand-secrets text entries)
  ;; $NAME becomes the .env value; unknown names stay literal.
  (let loop ((rest text) (out ""))
    (let ((dollar (string-index rest #\$)))
      (if (not dollar)
          (string-append out rest)
          (let* ((after (substring rest (+ dollar 1)))
                 (end (or (string-index after (lambda (c) (not (or (char-upper-case? c) (char-numeric? c) (char=? c #\_)))))
                          (string-length after)))
                 (name (substring after 0 end))
                 (value (assoc-ref entries name)))
            (loop (substring after end)
                  (string-append out (substring rest 0 dollar) (or (and (> end 0) value) (string-append "$" name)))))))))
(define (child-environment server)
  (let ((entries (dotenv-entries)))
    (append
     (filter-map (lambda (name) (let ((value (getenv name))) (and value (string-append name "=" value))))
                 '("PATH" "HOME" "LANG" "LC_ALL" "TERM" "TMPDIR"))
     (filter-map (lambda (name) (let ((value (assoc-ref entries name))) (and value (string-append name "=" value))))
                 (server-env-names server)))))

;; --- transports ------------------------------------------------------------
(define (temporary name)
  (let* ((port (mkstemp (string-append "/tmp/shift-mcp-" name "-XXXXXX"))) (path (port-filename port)))
    (close-port port) path))
(define (next-id! server)
  (set-server-next-id! server (+ 1 (server-next-id server)))
  (server-next-id server))
(define (stdio-start! server)
  (let* ((to-child (pipe)) (from-child (pipe))
         (stderr-path (temporary "stderr"))
         (sink (open-file stderr-path "w"))
         (pid (spawn (car (server-argv server)) (server-argv server)
                     #:input (car to-child) #:output (cdr from-child) #:error sink
                     #:environment (child-environment server))))
    (close-port (car to-child)) (close-port (cdr from-child)) (close-port sink)
    (setvbuf (cdr to-child) 'line)
    (set-server-stderr-path! server stderr-path)
    (set-server-pid! server pid) (set-server-in! server (cdr to-child)) (set-server-out! server (car from-child))))
(define (stdio-stop! server)
  (let ((pid (server-pid server)))
    (when pid
      (catch #t (lambda () (kill pid SIGTERM)) (lambda _ #f))
      (let loop ((waited 0))
        (let ((reaped (catch #t (lambda () (waitpid pid WNOHANG)) (lambda _ (cons pid #f)))))
          (when (and (= 0 (car reaped)) (< waited 2000)) (usleep 100000) (loop (+ waited 100)))
          (when (= 0 (car reaped)) (catch #t (lambda () (kill pid SIGKILL) (waitpid pid)) (lambda _ #f))))))
    (for-each (lambda (port) (when (and port (not (port-closed? port))) (close-port port)))
              (list (server-in server) (server-out server)))
    (set-server-pid! server #f) (set-server-in! server #f) (set-server-out! server #f)))
;; The last lines the child wrote to stderr, for a failure reason the user can act on.
(define (stderr-tail server)
  (let ((path (server-stderr-path server)))
    (if (and path (file-exists? path))
        (let* ((text (string-trim-both (call-with-input-file path get-string-all)))
               (lines (string-split text #\newline))
               (kept (if (> (length lines) 3) (list-tail lines (- (length lines) 3)) lines))
               (joined (string-join kept " | ")))
          (catch #t (lambda () (delete-file path)) (lambda _ #f))
          (if (> (string-length joined) 300) (substring joined 0 300) joined))
        "")))
(define (read-line-within port deadline)
  ;; One line, or #f when the deadline passes first.
  (let loop ()
    (let ((remaining (/ (- deadline (get-internal-real-time)) internal-time-units-per-second)))
      (cond ((<= remaining 0) #f)
            ((pair? (car (select (list port) '() '() (min remaining 0.25))))
             (let ((line (get-line port))) (if (eof-object? line) 'eof line)))
            (else (loop))))))
(define (stdio-rpc! server message id timeout)
  (let ((in (server-in server)) (out (server-out server)))
    (display (json-write message) in) (newline in) (force-output in)
    (if (not id)
        #t
        (let ((deadline (+ (get-internal-real-time) (* timeout internal-time-units-per-second))))
          (let loop ()
            (let ((line (read-line-within out deadline)))
              (cond ((not line) (error (format #f "no reply within ~as" timeout)))
                    ((eq? line 'eof) (error "server closed its output"))
                    (else
                     (let ((reply (catch #t (lambda () (json-read line)) (lambda _ #f))))
                       (if (and (json-object? reply) (equal? (json-object-ref reply "id" #f) id))
                           reply
                           (loop)))))))))))
(define (http-rpc! server message id timeout)
  (let* ((entries (dotenv-entries))
         (payload (temporary "payload")) (body (temporary "body")) (headers (temporary "headers"))
         (header-args
          (append-map (lambda (h) (list "-H" (string-append (car h) ": " (expand-secrets (cdr h) entries))))
                      (server-headers server))))
    (call-with-output-file payload (lambda (p) (display (json-write message) p)))
    (dynamic-wind
      (lambda () #t)
      (lambda ()
        (let* ((status (apply system* "curl" "-sS" "-m" (number->string timeout) "-o" body "-D" headers
                              "-H" "Content-Type: application/json" "-H" "Accept: application/json, text/event-stream"
                              (append (if (server-session-id server) (list "-H" (string-append "Mcp-Session-Id: " (server-session-id server))) '())
                                      header-args
                                      (list "--data-binary" (string-append "@" payload) (server-url server)))))
               (code (status:exit-val status)))
          (unless (eqv? code 0) (error (format #f "curl exited ~a" code)))
          (let* ((header-text (call-with-input-file headers get-string-all))
                 (lines (string-split header-text #\newline))
                 (http-status (let ((first (and (pair? lines) (string-tokenize (car lines)))))
                                (and first (>= (length first) 2) (string->number (cadr first)))))
                 (session (find (lambda (l) (string-prefix? "mcp-session-id:" (string-downcase l))) lines))
                 (event-stream? (any (lambda (l) (and (string-prefix? "content-type:" (string-downcase l))
                                                      (string-contains (string-downcase l) "text/event-stream")))
                                     lines))
                 (text (call-with-input-file body get-string-all)))
            (when session (set-server-session-id! server (string-trim-both (substring session (string-length "mcp-session-id:")))))
            (unless (and http-status (< http-status 300))
              (error (format #f "HTTP ~a: ~a" http-status (let ((t (string-trim-both text))) (if (> (string-length t) 200) (substring t 0 200) t)))))
            (if (not id)
                #t
                (let ((candidates (if event-stream?
                                      (filter-map (lambda (l) (and (string-prefix? "data:" l)
                                                                   (catch #t (lambda () (json-read (string-trim-both (substring l 5)))) (lambda _ #f))))
                                                  (string-split text #\newline))
                                      (list (catch #t (lambda () (json-read text)) (lambda _ #f))))))
                  (or (find (lambda (r) (and (json-object? r) (equal? (json-object-ref r "id" #f) id))) candidates)
                      (error "no matching JSON-RPC reply in the response")))))))
      (lambda () (for-each (lambda (f) (when (file-exists? f) (delete-file f))) (list payload body headers))))))
(define (rpc! server method params timeout)
  (let* ((id (next-id! server))
         (message (json-object (cons "jsonrpc" "2.0") (cons "id" id) (cons "method" method) (cons "params" params)))
         (reply (if (eq? (server-transport server) 'stdio)
                    (stdio-rpc! server message id timeout)
                    (http-rpc! server message id timeout)))
         (error-value (json-object-ref reply "error" #f)))
    (when error-value
      (error (format #f "~a: ~a" method (if (json-object? error-value) (json-object-ref error-value "message" "error") error-value))))
    (json-object-ref reply "result" (json-object))))
(define (notify! server method)
  (let ((message (json-object (cons "jsonrpc" "2.0") (cons "method" method))))
    (if (eq? (server-transport server) 'stdio)
        (stdio-rpc! server message #f 1)
        (catch #t (lambda () (http-rpc! server message #f connect-timeout)) (lambda _ #t)))))

;; --- connection ------------------------------------------------------------
(define (qualified server tool) (string-append (server-name server) "__" tool))
(define (tool-record server tool)
  (let* ((name (json-object-ref tool "name" ""))
         (annotations (json-object-ref tool "annotations" (json-object)))
         (hint (lambda (key default) (let ((v (json-object-ref annotations key default))) (if (boolean? v) v default))))
         (schema (json-object-ref tool "inputSchema" (json-object (cons "type" "object")))))
    (list (qualified server name)
          (json-object (cons "type" "function")
                       (cons "function" (json-object (cons "name" (qualified server name))
                                                     (cons "description" (let ((d (json-object-ref tool "description" ""))) (if (string? d) d "")))
                                                     (cons "parameters" (if (json-object? schema) schema (json-object (cons "type" "object")))))))
          `((read-only . ,(hint "readOnlyHint" #f))
            (destructive . ,(hint "destructiveHint" #t))
            (open-world . ,(hint "openWorldHint" #t))))))
(define (list-tools! server)
  (let loop ((cursor #f) (acc '()))
    (let* ((params (if cursor (json-object (cons "cursor" cursor)) (json-object)))
           (result (rpc! server "tools/list" params connect-timeout))
           (tools (filter json-object? (json-array-items (json-object-ref result "tools" (json-array)))))
           (next (json-object-ref result "nextCursor" #f))
           (acc (append acc tools)))
      (if (and (string? next) (< (length acc) 512)) (loop next acc) acc))))
(define (connect-now! server)
  (when (eq? (server-transport server) 'stdio) (stdio-start! server))
  (let* ((result (rpc! server "initialize"
                       (json-object (cons "protocolVersion" protocol-version) (cons "capabilities" (json-object))
                                    (cons "clientInfo" (json-object (cons "name" "shift") (cons "version" "0.1.0"))))
                       connect-timeout))
         (info (json-object-ref result "serverInfo" (json-object)))
         (instructions (json-object-ref result "instructions" ""))
         (first-line (if (string? instructions) (car (string-split instructions #\newline)) "")))
    (notify! server "notifications/initialized")
    (set-server-description! server
      (let ((text (if (string-null? (string-trim-both first-line)) (json-object-ref info "name" (server-name server)) first-line)))
        (if (> (string-length text) 200) (substring text 0 200) text)))
    (let* ((tools (list-tools! server))
           (kept (filter (lambda (t) (not (member (json-object-ref t "name" "") builtin-names))) tools))
           (refused (filter (lambda (t) (member (json-object-ref t "name" "") builtin-names)) tools)))
      (set-server-tools! server (map (lambda (t) (tool-record server t)) kept))
      (set-server-state! server 'connected)
      (set-server-reason! server
        (if (null? refused) #f
            (format #f "refused ~a: shadows a built-in" (string-join (map (lambda (t) (json-object-ref t "name" "")) refused) ", ")))))))
(define (mcp-connect! name)
  (let ((server (find-server name)))
    (unless server (error "no MCP server named" name))
    (with-mutex (server-lock server)
      (if (eq? (server-state server) 'connected)
          server
          (catch #t
            (lambda () (connect-now! server) server)
            (lambda (key . args)
              (catch #t (lambda () (stdio-stop! server)) (lambda _ #f))
              (set-server-state! server 'failed) (set-server-tools! server '()) (set-server-session-id! server #f)
              (set-server-reason! server
                (let ((tail (stderr-tail server)))
                  (if (string-null? tail) (error-text key args) (string-append (error-text key args) ": " tail))))
              (error (format #f "MCP server ~a failed: ~a" name (server-reason server)))))))))
(define (mcp-disconnect! name)
  (let ((server (find-server name)))
    (unless server (error "no MCP server named" name))
    (with-mutex (server-lock server)
      (stdio-stop! server)
      (set-server-state! server 'idle) (set-server-tools! server '()) (set-server-session-id! server #f) (set-server-reason! server #f))
    server))
(define (mcp-stop-all!)
  (for-each (lambda (server) (catch #t (lambda () (stdio-stop! server)) (lambda _ #f))) servers)
  (set! servers '()))

;; --- lookups the runtime uses -------------------------------------------------
(define (mcp-tools) (append-map server-tools (filter (lambda (s) (eq? (server-state s) 'connected)) servers)))
(define (mcp-server-tools name) (let ((s (find-server name))) (if s (server-tools s) '())))
(define (mcp-tool-name? name)
  (and (string? name)
       (let ((split (string-contains name "__")))
         (and split (find-server (substring name 0 split)) #t))))
(define (mcp-tool-server name)
  (let ((split (string-contains name "__"))) (and split (find-server (substring name 0 split)))))
(define (find-tool name) (assoc name (mcp-tools)))
(define (mcp-tool-schema name) (let ((t (find-tool name))) (and t (cadr t))))
(define (mcp-tool-hints name) (let ((t (find-tool name))) (and t (caddr t))))

;; tool_search: connect every idle server, then match SERVER__TOOL and the
;; description case-insensitively; "select:a,b" names tools exactly.
;; rerank, when given, sees the word-ranked candidates as ((name . description) ...)
;; before the cap and returns the names to keep, in order; it never sees select: queries.
(define* (mcp-search query #:key (rerank #f))
  (for-each (lambda (s) (when (eq? (server-state s) 'idle) (catch #t (lambda () (mcp-connect! (server-name s))) (lambda _ #f))))
            servers)
  (let* ((query (string-trim-both query))
         (tools (mcp-tools))
         (description (lambda (t) (json-object-ref (json-object-ref (cadr t) "function") "description" "")))
         (matches
          (if (string-prefix? "select:" query)
              (let ((wanted (map string-trim-both (string-split (substring query 7) #\,))))
                (filter (lambda (t) (member (car t) wanted)) tools))
              (let ((ranked (search-ranked query tools description)))
                (if (and rerank (pair? ranked))
                    (let ((kept (rerank query (map (lambda (t) (cons (car t) (description t))) ranked))))
                      (filter-map (lambda (name) (assoc name ranked)) kept))
                    ranked)))))
    (if (> (length matches) search-limit) (take matches search-limit) matches)))
;; Ranked by query words, not by the whole phrase: a server name matches all
;; of its tools, a word in the tool's own name counts double, a word in the
;; description once, and the whole phrase as a substring counts as well.

;; tools/call → (values ok? text). Text items join; other content is named
;; with its type and size rather than inlined.
(define (content-text item)
  (let ((type (json-object-ref item "type" "")))
    (cond ((equal? type "text") (let ((t (json-object-ref item "text" ""))) (if (string? t) t "")))
          ((member type '("image" "audio"))
           (format #f "[~a ~a, ~a bytes base64]" type (json-object-ref item "mimeType" "?")
                   (string-length (let ((d (json-object-ref item "data" ""))) (if (string? d) d "")))))
          ((equal? type "resource")
           (let* ((resource (json-object-ref item "resource" (json-object)))
                  (text (json-object-ref resource "text" #f)))
             (string-append "[resource " (let ((u (json-object-ref resource "uri" ""))) (if (string? u) u "")) "]"
                            (if (string? text) (string-append "\n" text) ""))))
          (else (format #f "[~a content]" type)))))
(define (mcp-call! name arguments)
  (let ((server (mcp-tool-server name)))
    (unless (and server (find-tool name)) (error "unknown MCP tool; use tool_search first" name))
    (let* ((tool (substring name (+ 2 (string-contains name "__"))))
           (result (with-mutex (server-lock server)
                     (rpc! server "tools/call"
                           (json-object (cons "name" tool) (cons "arguments" (if (json-object? arguments) arguments (json-object))))
                           call-timeout)))
           (content (filter json-object? (json-array-items (json-object-ref result "content" (json-array)))))
           (text (string-join (map content-text content) "\n"))
           ;; An oversized MCP result spills to a file like any other tool
           ;; output, labelled with the server so the file says where it came
           ;; from. Integration responses are the ones most likely to be large.
           (windowed (bounded text (server-name server))))
      (values (not (json-object-ref result "isError" #f)) windowed))))

(define (mcp-servers-json)
  (apply json-array
    (map (lambda (s)
           (json-object (cons "name" (server-name s)) (cons "source" (server-source s))
                        (cons "transport" (symbol->string (server-transport s)))
                        (cons "state" (symbol->string (server-state s)))
                        (cons "reason" (or (server-reason s) json-null))
                        (cons "description" (server-description s))
                        (cons "tools" (length (server-tools s)))))
         servers)))
(define (mcp-prompt-block)
  (let ((listed (filter (lambda (s) (not (string=? (server-name s) "pack"))) servers)))
    (if (null? listed)
        ""
        (string-append
         "\n\n<mcp_servers>\nExternal tool servers. Their tools are not listed here: call tool_search with a few words about what you need (or select:SERVER__TOOL) and the matching tools become callable for the rest of this turn.\n"
         (string-join (map (lambda (s) (string-append "- " (server-name s)
                                                     (if (string-null? (server-description s)) "" (string-append ": " (server-description s)))))
                           listed) "\n")
         "\n</mcp_servers>"))))
