(define-module (live-agent models)
  #:use-module (srfi srfi-1)
  #:use-module (live-agent builtins)
  #:use-module (live-agent settings)
  #:use-module (live-agent json)
  #:use-module (shift http)
  #:export (model-select! model-list! effective-effort effective-fast? show-model
            model-context-limit))
(define metadata '())
(define (claude-cap name model) ((builtin-ref 'claude name) model))
(define (effective-effort generation)
  (let ((provider (setting-ref generation 'agent-provider))
        (model (setting-ref generation 'agent-model)) (requested (setting-ref generation 'effort)))
    (if (or (and (eq? provider 'claude) (claude-cap 'claude-effort? model))
            (and (eq? provider 'openai) ((builtin-ref 'openai 'openai-effort?) model)
                 (memq requested '(default low medium high)))) requested 'default)))
(define (effective-fast? generation)
  (and (setting-ref generation 'fast)
       (case (setting-ref generation 'agent-provider)
         ((claude) (claude-cap 'claude-fast? (setting-ref generation 'agent-model)))
         ((openai) ((builtin-ref 'openai 'openai-fast?) (setting-ref generation 'agent-model)))
         (else #f))))
(define (show-model generation)
  (let ((effort (effective-effort generation)) (fast? (effective-fast? generation)))
    (format #t "~a/~a · thinking ~a · effort ~a · fast ~a~%"
      (setting-ref generation 'agent-provider) (setting-ref generation 'agent-model)
      (if (eq? (setting-ref generation 'agent-provider) 'openai) 'provider-managed
          (setting-ref generation 'agent-thinking)) effort (if fast? 'on 'off))
    (when (not (eq? effort (setting-ref generation 'effort)))
      (display "Saved effort is unavailable for this model.\n"))
    (when (and (setting-ref generation 'fast) (not fast?))
      (display "Saved fast mode is unavailable for this model.\n"))))
(define (model-select! value)
  (let ((slash (string-index value #\/)))
    (unless slash (error "use /model PROVIDER/MODEL, e.g. claude/claude-sonnet-4-6"))
    (let ((provider (string->symbol (substring value 0 slash)))
          (model (substring value (+ slash 1))))
      (unless (and (memq provider '(claude ollama openai)) (builtin-enabled? provider))
        (error "provider is unavailable" provider))
      (settings-set!
       (list (cons 'agent-provider provider) (cons 'agent-model model) (cons 'context-limit #f)
             (cons 'agent-base-url (case provider
               ((claude) "https://api.anthropic.com/v1") ((openai) "https://api.openai.com/v1")
               (else "http://127.0.0.1:11434")))
             (cons 'agent-api-key-environment (case provider
               ((claude) "CLAUDE_API_KEY") ((openai) "OPENAI_API_KEY") (else #f))))))))
(define* (model-list! generation #:optional (display? #t))
  (let* ((provider (setting-ref generation 'agent-provider))
         (base (without-trailing-slash (setting-ref generation 'agent-base-url)))
         (env (setting-ref generation 'agent-api-key-environment))
         (key (and env (getenv env)))
         (root (if (eq? provider 'claude)
           (begin
             (unless key (error "CLAUDE_API_KEY is missing"))
             (when (or (string-index key #\newline) (string-index key #\return)) (error "invalid key"))
             (curl-get-json (string-append base "/models?limit=100") #f
               (string-append "x-api-key: " key "\nanthropic-version: 2023-06-01\n")))
           (curl-get-json (string-append base (if (eq? provider 'ollama) "/api/tags" "/models")) key)))
         (models (json-array-items (json-object-ref (json-read root) (if (eq? provider 'ollama) "models" "data")))))
    (for-each (lambda (model)
      (let ((id (json-object-ref model (if (eq? provider 'ollama) "name" "id"))))
        (set! metadata (acons (cons provider id) model metadata))
        (when display? (format #t "~a/~a~%" provider id)))) models)))
(define (model-context-limit generation)
  (let ((identity (cons (setting-ref generation 'agent-provider) (setting-ref generation 'agent-model))))
    (when (and (eq? (car identity) 'claude) (not (assoc identity metadata)))
      ;; Discover the selected account's current window once per process.
      ;; A failed discovery remains unknown rather than inventing a limit.
      (set! metadata (acons identity (json-object) metadata))
      (catch #t (lambda () (model-list! generation #f)) (lambda _ #f))))
  (or (setting-ref generation 'context-limit)
      (let* ((model (assoc-ref metadata (cons (setting-ref generation 'agent-provider)
                                            (setting-ref generation 'agent-model))))
             (limit (and model (json-object-ref model "max_input_tokens" #f))))
        (and (number? limit) (> limit 0) limit))))
