;; Plugins bundle the data Shift already treats as user-owned: MCP servers,
;; skills, panes, themes, allowlist proposals, .env needs, secret sources and
;; live-image artifacts. A plugin is a folder with a plugin.scm manifest read
;; like a pane pack and never evaluated. Installed plugins are on by default;
;; the `plugins` setting turns one off or on per scope, user over project.
(define-module (live-agent plugins)
  #:use-module (ice-9 textual-ports)
  #:use-module (ice-9 ftw)
  #:use-module (ice-9 format)
  #:use-module (srfi srfi-1)
  #:use-module (live-agent json)
  #:export (plugins-init! plugin-index plugin-find plugins-json parse-plugin-manifest check-plugin-dir
            plugin-field plugin-available?))

(define max-manifest-bytes 32768)
(define sources '())   ; ((label . directory-of-plugins) ...) low to high precedence
(define singles '())   ; ((label . plugin-dir) ...) a project's own .shift-plugin
(define index '())
(define signature #f)

(define (plugin-field plugin key) (assq-ref plugin key))
(define (valid-name? name)
  (and (string? name) (<= 1 (string-length name) 32)
       (string-every (lambda (c) (or (char-lower-case? c) (char-numeric? c) (char=? c #\-))) name)))
(define (env-name? value)
  (and (symbol? value)
       (string-every (lambda (c) (or (char-upper-case? c) (char-numeric? c) (char=? c #\_))) (symbol->string value))))
(define (relative-file? value)
  (and (string? value) (not (string-null? value)) (not (string-prefix? "/" value)) (not (string-contains value ".."))))

;; The manifest: (plugin NAME VERSION) first, then sections in any order.
(define (parse-plugin-manifest text directory source)
  (let ((data (call-with-input-string text
                (lambda (p) (let ((form (read p)))
                  (unless (eof-object? (read p)) (error "a plugin manifest is one list of sections")) form)))))
    (unless (and (list? data) (pair? data) (list? (car data)) (eq? (caar data) 'plugin)
                 (= (length (car data)) 3) (valid-name? (cadar data)) (string? (caddar data)))
      (error "a manifest starts with (plugin \"name\" \"version\")"))
    (let loop ((rest (cdr data))
               (plugin (list (cons 'name (cadar data)) (cons 'version (caddar data)) (cons 'path directory) (cons 'source source)
                             (cons 'description "") (cons 'requires '()) (cons 'mcp '()) (cons 'skills #f) (cons 'panes #f)
                             (cons 'themes '()) (cons 'agent '()) (cons 'allow-run '()) (cons 'allow-mcp '())
                             (cons 'env '()) (cons 'secrets '()))))
      (define (put key value) (acons key value (filter (lambda (e) (not (eq? (car e) key))) plugin)))
      (if (null? rest)
          plugin
          (let ((section (car rest)))
            (unless (and (pair? section) (symbol? (car section)) (list? (cdr section)))
              (error "manifest sections are lists headed by a symbol" section))
            (loop (cdr rest)
                  (case (car section)
                    ((description) (unless (and (= (length section) 2) (string? (cadr section)) (<= (string-length (cadr section)) 200))
                                     (error "description takes one string up to 200 characters" section))
                     (put 'description (cadr section)))
                    ((requires) (unless (every (lambda (r) (and (list? r) (= (length r) 2) (eq? (car r) 'command) (string? (cadr r)))) (cdr section))
                                  (error "requires takes (command \"name\") entries" section))
                     (put 'requires (map cadr (cdr section))))
                    ((mcp) (unless (every (lambda (s) (and (list? s) (eq? (car s) 'server))) (cdr section))
                             (error "mcp takes (server ...) forms as in .shift/mcp.scm" section))
                     (put 'mcp (cdr section)))
                    ((skills) (unless (and (= (length section) 2) (relative-file? (cadr section))) (error "skills takes one folder" section))
                     (put 'skills (string-append directory "/" (cadr section))))
                    ((panes) (unless (and (= (length section) 2) (relative-file? (cadr section))) (error "panes takes one file" section))
                     (put 'panes (string-append directory "/" (cadr section))))
                    ((theme) (unless (every relative-file? (cdr section)) (error "theme takes files" section))
                     (put 'themes (append (plugin-field plugin 'themes) (map (lambda (f) (string-append directory "/" f)) (cdr section)))))
                    ((agent) (unless (every relative-file? (cdr section)) (error "agent takes artifact files" section))
                     (put 'agent (append (plugin-field plugin 'agent) (map (lambda (f) (string-append directory "/" f)) (cdr section)))))
                    ((allow-run) (unless (every (lambda (p) (and (list? p) (pair? p) (every string? p))) (cdr section))
                                   (error "allow-run takes argv prefixes" section))
                     (put 'allow-run (cdr section)))
                    ((allow-mcp) (unless (every (lambda (n) (and (string? n) (string-contains n "__"))) (cdr section))
                                   (error "allow-mcp takes SERVER__TOOL names" section))
                     (put 'allow-mcp (cdr section)))
                    ((env) (unless (every env-name? (cdr section)) (error "env takes variable names" section))
                     (put 'env (map symbol->string (cdr section))))
                    ((secret) (unless (and (= (length section) 3) (env-name? (cadr section)) (list? (caddr section))
                                           (= (length (caddr section)) 2) (eq? (car (caddr section)) 'op) (string? (cadr (caddr section))))
                                (error "secret takes NAME (op \"op://vault/item/field\")" section))
                     (put 'secrets (append (plugin-field plugin 'secrets) (list (cons (symbol->string (cadr section)) (cadr (caddr section)))))))
                    (else (error "unknown manifest section" (car section))))))))))

(define (read-plugin directory source)
  (let ((manifest (string-append directory "/plugin.scm")))
    (catch #t
      (lambda ()
        (when (> (stat:size (stat manifest)) max-manifest-bytes) (error "plugin.scm exceeds 32 KiB"))
        (let* ((plugin (parse-plugin-manifest (call-with-input-file manifest get-string-all #:encoding "UTF-8") directory source))
               (missing (filter (lambda (c) (not (search-path (parse-path (or (getenv "PATH") "")) c))) (plugin-field plugin 'requires))))
          (for-each (lambda (key)
                      (let ((value (plugin-field plugin key)))
                        (cond ((and (string? value) (not (file-exists? value))) (error (format #f "~a folder or file is missing: ~a" key value)))
                              ((list? value) (for-each (lambda (f) (unless (file-exists? f) (error (format #f "~a file is missing: ~a" key f)))) value)))))
                    '(skills panes themes agent))
          (append plugin (list (cons 'valid #t) (cons 'error #f) (cons 'missing missing)))))
      (lambda (key . args)
        (list (cons 'name (basename directory)) (cons 'version "") (cons 'path directory) (cons 'source source)
              (cons 'description "") (cons 'requires '()) (cons 'mcp '()) (cons 'skills #f) (cons 'panes #f) (cons 'themes '())
              (cons 'agent '()) (cons 'allow-run '()) (cons 'allow-mcp '()) (cons 'env '()) (cons 'secrets '())
              (cons 'valid #f)
              (cons 'error (if (and (>= (length args) 2) (string? (cadr args)))
                               (if (and (>= (length args) 3) (pair? (caddr args))) (format #f "~a ~s" (cadr args) (car (caddr args))) (cadr args))
                               (format #f "~a" key)))
              (cons 'missing '()))))))

(define (plugin-available? plugin) (and (plugin-field plugin 'valid) (null? (plugin-field plugin 'missing))))

;; (plugins-init! install-root project-dir user-dir extra-dirs): bundled
;; plugins ship with the install, user ones live under the config, project
;; ones under .shift/plugins, a tool's own repository carries .shift-plugin,
;; and plugin-dirs adds folders of plugins from elsewhere. Later wins by name.
(define (plugins-init! install-root project-dir user-dir extra-dirs)
  (set! sources
    (filter (lambda (e) (cdr e))
      (append (list (cons "bundled" (and install-root (string-append install-root "/plugins")))
                    (cons "user" (and user-dir (string-append user-dir "/plugins"))))
              (map (lambda (d) (cons "dir" d)) (or extra-dirs '()))
              (list (cons "project" (and project-dir (string-append project-dir "/.shift/plugins")))))))
  (set! singles (if (and project-dir (file-exists? (string-append project-dir "/.shift-plugin/plugin.scm")))
                    (list (cons "repository" (string-append project-dir "/.shift-plugin")))
                    '()))
  (set! index '()) (set! signature #f))
(define (entries directory)
  (catch #t
    (lambda () (sort (filter (lambda (n) (not (member n '("." "..")))) (scandir directory)) string<?))
    (lambda _ '())))
(define (plugin-dirs)
  (append
   (append-map (lambda (s) (filter-map (lambda (n) (let ((d (string-append (cdr s) "/" n)))
                                                    (and (file-exists? (string-append d "/plugin.scm")) (cons (car s) d))))
                                      (entries (cdr s))))
               sources)
   singles))
(define (current-signature)
  (map (lambda (e) (cons (cdr e) (catch #t (lambda () (stat:mtime (stat (string-append (cdr e) "/plugin.scm")))) (lambda _ #f))))
       (plugin-dirs)))
(define (rebuild!)
  (set! index
    (let loop ((dirs (plugin-dirs)) (acc '()))
      (if (null? dirs)
          (reverse acc)
          (let ((plugin (read-plugin (cdar dirs) (caar dirs))))
            (loop (cdr dirs)
                  (cons plugin (filter (lambda (p) (not (string=? (plugin-field p 'name) (plugin-field plugin 'name)))) acc))))))))
(define (plugin-index)
  (let ((now (current-signature)))
    (unless (equal? now signature) (set! signature now) (rebuild!))
    index))
(define (plugin-find name) (find (lambda (p) (string=? (plugin-field p 'name) name)) (plugin-index)))
(define* (check-plugin-dir #:optional (directory ".shift-plugin"))
  (let ((plugin (read-plugin directory "check")))
    (unless (plugin-field plugin 'valid) (error (plugin-field plugin 'error)))
    plugin))
;; enabled? is supplied by the caller, which owns the settings.
(define (plugins-json enabled?)
  (apply json-array
    (map (lambda (p)
           (json-object (cons "name" (plugin-field p 'name)) (cons "version" (plugin-field p 'version))
                        (cons "description" (plugin-field p 'description)) (cons "source" (plugin-field p 'source))
                        (cons "path" (plugin-field p 'path)) (cons "valid" (plugin-field p 'valid))
                        (cons "error" (or (plugin-field p 'error) json-null))
                        (cons "missing" (apply json-array (plugin-field p 'missing)))
                        (cons "enabled" (and (plugin-available? p) (enabled? (plugin-field p 'name))))
                        (cons "contributes" (apply json-array
                          (filter identity
                            (list (and (pair? (plugin-field p 'mcp)) (format #f "~a mcp" (length (plugin-field p 'mcp))))
                                  (and (plugin-field p 'skills) "skills")
                                  (and (plugin-field p 'panes) "panes")
                                  (and (pair? (plugin-field p 'themes)) "theme")
                                  (and (pair? (plugin-field p 'agent)) "agent")
                                  (and (pair? (plugin-field p 'allow-run)) (format #f "~a run prefixes" (length (plugin-field p 'allow-run))))
                                  (and (pair? (plugin-field p 'secrets)) "secrets")))))))
         (plugin-index))))
