(define-module (live-agent policy)
  #:use-module (srfi srfi-1)
  #:use-module (live-agent json)
  #:export (tool-decision run-argv-of run-allowed?))
;; No live-image binding can override this decision. Three modes: manual asks
;; before each tool except allowlisted runs, plan permits reads only, and
;; autopilot runs everything without asking. Nothing infers approval.
(define (run-argv-of arguments)
  (let ((value (json-object-ref arguments "argv" #f)))
    (if (and (json-array? value) (every string? (json-array-items value)))
        (json-array-items value)
        '())))
;; Exact leading-element match: ("cargo" "test") allows ("cargo" "test" "--" "x")
;; and never ("cargo" "publish").
(define (run-allowed? argv prefixes)
  (and (pair? argv)
       (any (lambda (prefix)
              (and (<= (length prefix) (length argv))
                   (equal? prefix (take argv (length prefix)))))
            prefixes)))
(define* (tool-decision mode name arguments #:optional (run-allow '()))
  (let ((read-only? (or (member name '("read" "rg" "traces" "status" "diff" "skill" "job"))
                        (and (string=? name "ui") (equal? (json-object-ref arguments "action" "get") "get"))
                        (and (string=? name "extension")
                             (equal? (json-object-ref arguments "action" #f) "list"))))
        (allowed-run? (and (string=? name "run")
                           (run-allowed? (run-argv-of arguments) run-allow))))
    (case mode
      ((manual) (if allowed-run? 'allow 'ask))
      ((plan) (if read-only? 'allow 'deny))
      ((autopilot) 'allow)
      (else 'deny))))
