(define-module (live-agent policy)
  #:use-module (srfi srfi-1)
  #:use-module (live-agent json)
  #:export (tool-decision run-argv-of run-allowed?))
;; No live-image binding can override this decision. Auto remains conservative
;; until an approval model has passed held-out evaluation; it does not guess.
(define (run-argv-of arguments)
  (let ((value (json-object-ref arguments "argv" #f)))
    (if (and (json-array? value) (every string? (json-array-items value)))
        (json-array-items value)
        '())))
;; Exact leading-element match: ("cargo" "test") allows ("cargo" "test" "--" "x")
;; and never ("cargo" "publish").
(define (run-allowed? argv prefixes)
  (and (pair? argv)
       (any (lambda (prefix)
              (and (<= (length prefix) (length argv))
                   (equal? prefix (take argv (length prefix)))))
            prefixes)))
(define* (tool-decision mode name arguments #:optional (run-allow '()))
  (let ((read-only? (or (member name '("read" "rg" "traces" "status" "diff"))
                        (and (string=? name "ui") (equal? (json-object-ref arguments "action" "get") "get"))
                        (and (string=? name "extension")
                             (equal? (json-object-ref arguments "action" #f) "list"))))
        (allowed-run? (and (string=? name "run")
                           (run-allowed? (run-argv-of arguments) run-allow))))
    (case mode
      ((manual) 'ask)
      ((plan) (if read-only? 'allow 'deny))
      ((accept) (if (or read-only? allowed-run? (member name '("write" "edit" "apply_patch" "ui"))) 'allow 'ask))
      ((auto) (if (or read-only? allowed-run? (string=? name "ui")) 'allow 'ask))
      (else 'deny))))
