(define-module (live-agent settings)
  #:use-module (ice-9 textual-ports)
  #:use-module (srfi srfi-1)
  #:use-module (live-agent json)
  #:use-module (live-agent generation)
  #:export (settings-init! setting-ref setting-set! setting-set-json! settings-set! settings-save!
            settings-show settings-object load-dotenv!))

;; Data only: never evaluate persisted preferences as Scheme. Live image code
;; cannot access this module or change the process-owned execution mode.
(define (assq-delete-all key entries) (filter (lambda (p) (not (eq? (car p) key))) entries))
(define preferences '())
(define sources '())
(define project-file #f)
(define session-file #f)
(define user-file #f)
(define defaults '((mode . manual) (effort . default) (fast . #f)
                   (context-limit . #f) (output-reserve . 8192)
                   (run-allow . ()) (run-backend . local) (run-sandbox . #f)
                   (turn-token-budget . #f) (show-work . #t)))
(define bindings '(agent-provider agent-model agent-base-url agent-api-key-environment
                  agent-stream? agent-thinking agent-keep-alive agent-max-tool-rounds))
(define (valid? key value)
  (case key
    ((agent-max-tool-rounds) (and (integer? value) (>= value 0) (<= value 64)))
    ;; Cumulative uncached prompt plus completion tokens one turn may spend
    ;; before it is ended with a recorded reason.
    ((turn-token-budget) (or (not value) (and (integer? value) (>= value 1024))))
    ((agent-provider) (memq value '(ollama openai claude)))
    ((agent-model agent-base-url) (and (string? value) (not (string-null? value))))
    ((agent-api-key-environment) (or (not value) (string? value)))
    ;; show-work covers the per-call tool echo and the end-of-turn receipt text.
    ((agent-stream? fast show-work) (boolean? value))
    ((agent-thinking) (or (boolean? value) (memq value '(low medium high))))
    ((agent-keep-alive) (or (string? value) (number? value)))
    ((mode) (memq value '(manual plan accept auto)))
    ((effort) (memq value '(default low medium high max)))
    ((context-limit) (or (not value) (and (integer? value) (>= value 1024))))
    ((output-reserve) (and (integer? value) (>= value 1024) (<= value 65536)))
    ;; Exact argv prefixes the process may run without asking in accept/auto.
    ((run-allow) (and (list? value)
                      (every (lambda (prefix)
                               (and (pair? prefix) (every (lambda (s) (and (string? s) (not (string-null? s)))) prefix)))
                             value)))
    ((run-backend) (memq value '(local agentkernel)))
    ((run-sandbox) (or (not value) (and (string? value) (not (string-null? value)))))
    (else #f)))
(define (decode key value)
  (cond
   ((and (string? value) (memq key '(agent-provider agent-thinking mode effort run-backend)))
    (string->symbol value))
   ((and (eq? key 'run-allow) (json-array? value))
    (map (lambda (prefix) (if (json-array? prefix) (json-array-items prefix) prefix))
         (json-array-items value)))
   (else value)))
(define (encoded value)
  (cond ((symbol? value) (symbol->string value))
        ((list? value) (apply json-array (map encoded value)))
        (else value)))
(define (ensure-directory path)
  (unless (file-exists? path)
    (ensure-directory (dirname path)) (mkdir path #o700)))
(define (write-settings path entries)
  (ensure-directory (dirname path))
  (let* ((port (mkstemp (string-append path ".XXXXXX")))
         (temporary (port-filename port)))
    (dynamic-wind
      (lambda () #t)
      (lambda ()
        (display (json-write (apply json-object
                        (map (lambda (entry) (cons (symbol->string (car entry))
                                                   (encoded (cdr entry)))) entries))) port)
        (newline port) (close-port port) (rename-file temporary path))
      (lambda ()
        (unless (port-closed? port) (close-port port))
        (when (file-exists? temporary) (delete-file temporary))))))
;; Keys that were renamed; files written by earlier builds still load.
(define (rename key) (if (eq? key 'show-tools) 'show-work key))
(define (load-settings! path source)
  (when (file-exists? path)
    (when (> (stat:size (stat path)) 32768) (error "settings file too large" path))
    (let ((value (call-with-input-file path (lambda (p) (json-read (get-string-all p))))))
      (unless (json-object? value) (error "settings must be an object" path))
      (for-each
       (lambda (entry)
         (let* ((key (rename (string->symbol (car entry)))) (value (decode key (cdr entry))))
           (unless (valid? key value) (error "invalid setting" path key))
           (set! preferences (acons key value (assq-delete-all key preferences)))
           (set! sources (acons key source (assq-delete-all key sources)))))
       (json-object-entries value)))))
(define (settings-init! project-state session-state)
  (set! preferences '()) (set! sources '())
  (set! project-file (string-append project-state "/settings.json"))
  (set! session-file (and session-state (string-append session-state "/settings.json")))
  (set! user-file (string-append (or (getenv "XDG_CONFIG_HOME")
                                   (string-append (getenv "HOME") "/.config"))
                               "/shift/settings.json"))
  (load-settings! user-file 'user)
  (load-settings! project-file 'project)
  (when session-file (load-settings! session-file 'session)))
(define (setting-ref generation key)
  (let ((entry (assq key preferences)))
    (cond (entry (cdr entry))
          ((assq key defaults) => cdr)
          (else (generation-ref generation key)))))
(define (settings-object generation)
  (apply json-object
    (map (lambda (key) (cons (symbol->string key) (encoded (setting-ref generation key))))
         (append bindings (map car defaults)))))
(define (settings-set! entries)
  (for-each (lambda (entry)
              (unless (valid? (car entry) (cdr entry)) (error "invalid setting" (car entry)))) entries)
  (let ((next (fold (lambda (entry acc)
                     (acons (car entry) (cdr entry) (assq-delete-all (car entry) acc)))
                   preferences entries)))
    ;; Only publish changes after durable storage succeeds.
    (when session-file (write-settings session-file next))
    (set! preferences next)
    (for-each (lambda (entry)
                (set! sources (acons (car entry) 'session (assq-delete-all (car entry) sources)))) entries)))
(define (setting-set! key value) (settings-set! (list (cons key value))))
;; For --set KEY=JSON: the value is parsed as JSON and decoded like a file.
(define (setting-set-json! key text)
  (let ((value (catch #t (lambda () (json-read text))
                 (lambda _ (error "setting value must be JSON" key text)))))
    (setting-set! key (decode key value))))
(define (settings-save! generation scope)
  (let ((path (if (eq? scope 'user) user-file project-file)))
    (write-settings path (map (lambda (entry) (cons (string->symbol (car entry))
                                                   (decode (string->symbol (car entry)) (cdr entry))))
                             (json-object-entries (settings-object generation))))
    path))
(define (settings-show generation)
  (for-each
   (lambda (key)
     (format #t "~a ~a (~a)~%" key (setting-ref generation key)
             (or (assq-ref sources key) 'default)))
   (append bindings (map car defaults))))

(define (load-dotenv! path)
  ;; A deliberately small dotenv reader; no shell substitution or evaluation.
  (when (file-exists? path)
    (call-with-input-file path
      (lambda (port)
        (let loop ((line (get-line port)))
          (unless (eof-object? line)
            (let* ((line (string-trim-both line))
                   (line (if (string-prefix? "export " line) (substring line 7) line))
                   (equal (string-index line #\=)))
              (when (and equal (not (string-prefix? "#" line)))
                (let* ((name (string-trim-both (substring line 0 equal)))
                       (value (string-trim-both (substring line (+ equal 1)))))
                  (when (and (not (string-null? name))
                             (string-every (lambda (c) (or (char-alphabetic? c) (char-numeric? c) (char=? c #\_))) name)
                             (not (getenv name)))
                    (when (and (>= (string-length value) 2)
                               (memv (string-ref value 0) '(#\" #\'))
                               (char=? (string-ref value 0) (string-ref value (- (string-length value) 1))))
                      (set! value (substring value 1 (- (string-length value) 1))))
                    (setenv name value)))))
            (loop (get-line port))))))))
