(define-module (live-agent settings)
  #:use-module (ice-9 textual-ports)
  #:use-module (srfi srfi-1)
  #:use-module (live-agent json)
  #:use-module (live-agent generation)
  #:export (settings-init! setting-ref setting-set! setting-set-json! settings-set! settings-save!
            settings-show settings-object setting-source load-dotenv! allow-run! deny-run! run-allow-entries))

;; Data only: never evaluate persisted preferences as Scheme. Live image code
;; cannot access this module or change the process-owned execution mode.
(define (assq-delete-all key entries) (filter (lambda (p) (not (eq? (car p) key))) entries))
(define preferences '())
(define sources '())
;; The run allowlist is the one setting that unions across scopes instead of
;; the nearest scope replacing the rest: a prefix allowed for the user, the
;; project (committable .shift/settings.json) or this session all count.
(define project-file #f)
(define session-file #f)
(define user-file #f)
(define allow-lists '((user . ()) (project . ()) (session . ())))
(define (allow-scope-set! scope prefixes)
  (set! allow-lists (acons scope prefixes (assq-delete-all scope allow-lists))))
(define (union-allow-lists)
  (fold (lambda (scope acc)
          (fold (lambda (prefix acc) (if (member prefix acc) acc (append acc (list prefix))))
                acc (or (assq-ref allow-lists scope) '())))
        '() '(user project session)))
(define (refresh-run-allow!)
  (set! preferences (acons 'run-allow (union-allow-lists) (assq-delete-all 'run-allow preferences))))
(define (scope-file scope)
  (case scope ((user) user-file) ((project) project-file) ((session) session-file) (else #f)))
(define (file-entries path)
  (if (and path (file-exists? path))
      (let ((value (call-with-input-file path (lambda (p) (json-read (get-string-all p))))))
        (map (lambda (entry) (cons (rename (string->symbol (car entry))) (decode (rename (string->symbol (car entry))) (cdr entry))))
             (json-object-entries value)))
      '()))
;; (allow-run! prefix scope) persists an argv prefix at that scope and makes
;; it effective at once; session prefixes go to the session file like every
;; other preference, project and user ones touch only run-allow in their file.
(define (allow-run! prefix scope)
  (unless (valid? 'run-allow (list prefix)) (error "an allowlist prefix is a non-empty argv" prefix))
  (unless (memq scope '(user project session)) (error "scope must be user, project or session" scope))
  (let ((current (or (assq-ref allow-lists scope) '())))
    (unless (member prefix current)
      (let ((next (append current (list prefix))) (path (scope-file scope)))
        (cond
         ((eq? scope 'session)
          (when path (write-settings path (acons 'run-allow next (assq-delete-all 'run-allow (file-entries path))))))
         (else
          (unless path (error "no settings file for scope" scope))
          (write-settings path (acons 'run-allow next (assq-delete-all 'run-allow (file-entries path))))))
        (allow-scope-set! scope next)
        (refresh-run-allow!)))
    (assq-ref allow-lists scope)))
;; (deny-run! prefix) removes a prefix from every scope that holds it,
;; rewriting those files, and reports the scopes it left.
(define (deny-run! prefix)
  (let ((removed (filter (lambda (scope) (member prefix (or (assq-ref allow-lists scope) '()))) '(user project session))))
    (when (null? removed) (error "that prefix is not in the allowlist" (string-join prefix " ")))
    (for-each (lambda (scope)
                (let ((next (delete prefix (assq-ref allow-lists scope))) (path (scope-file scope)))
                  (when path (write-settings path (acons 'run-allow next (assq-delete-all 'run-allow (file-entries path)))))
                  (allow-scope-set! scope next)))
              removed)
    (refresh-run-allow!)
    removed))
;; Oldest scope first: ((prefix . scope) ...) for /allow-run listings.
(define (run-allow-entries)
  (append-map (lambda (scope) (map (lambda (prefix) (cons prefix scope)) (or (assq-ref allow-lists scope) '())))
              '(user project session)))
;; SHIFT_PROVIDER_RETRIES sets the process-wide default so test harnesses can
;; make planned provider errors fail fast; the setting still wins.
(define default-provider-retries
  (let ((value (getenv "SHIFT_PROVIDER_RETRIES")))
    (or (and value (string->number value)) 3)))
(define defaults `((mode . manual) (effort . default) (fast . #f)
                   (context-limit . #f) (output-reserve . 8192)
                   (run-allow . ()) (run-backend . local) (run-sandbox . #f)
                   (turn-token-budget . #f) (show-work . #t)
                   (provider-retries . ,default-provider-retries)))
(define bindings '(agent-provider agent-model agent-base-url agent-api-key-environment
                  agent-stream? agent-thinking agent-keep-alive agent-max-tool-rounds))
(define (valid? key value)
  (case key
    ((agent-max-tool-rounds) (and (integer? value) (>= value 0) (<= value 64)))
    ;; Retries of a provider request that failed with 429, 5xx, or a connection
    ;; error before any of the response was consumed.
    ((provider-retries) (and (integer? value) (>= value 0) (<= value 10)))
    ;; Cumulative uncached prompt plus completion tokens one turn may spend
    ;; before it is ended with a recorded reason.
    ((turn-token-budget) (or (not value) (and (integer? value) (>= value 1024))))
    ((agent-provider) (memq value '(ollama openai claude)))
    ((agent-model agent-base-url) (and (string? value) (not (string-null? value))))
    ((agent-api-key-environment) (or (not value) (string? value)))
    ;; show-work covers the per-call tool echo and the end-of-turn receipt text.
    ((agent-stream? fast show-work) (boolean? value))
    ((agent-thinking) (or (boolean? value) (memq value '(low medium high))))
    ((agent-keep-alive) (or (string? value) (number? value)))
    ((mode) (memq value '(manual plan autopilot)))
    ((effort) (memq value '(default low medium high max)))
    ((context-limit) (or (not value) (and (integer? value) (>= value 1024))))
    ((output-reserve) (and (integer? value) (>= value 1024) (<= value 65536)))
    ;; Exact argv prefixes the process may run without asking in accept/auto.
    ((run-allow) (and (list? value)
                      (every (lambda (prefix)
                               (and (pair? prefix) (every (lambda (s) (and (string? s) (not (string-null? s)))) prefix)))
                             value)))
    ((run-backend) (memq value '(local agentkernel)))
    ((run-sandbox) (or (not value) (and (string? value) (not (string-null? value)))))
    (else #f)))
(define (decode key value)
  (cond
   ((and (string? value) (memq key '(mode agent-provider agent-thinking effort run-backend)))
    (string->symbol value))
   ((and (eq? key 'run-allow) (json-array? value))
    (map (lambda (prefix) (if (json-array? prefix) (json-array-items prefix) prefix))
         (json-array-items value)))
   (else value)))
(define (encoded value)
  (cond ((symbol? value) (symbol->string value))
        ((list? value) (apply json-array (map encoded value)))
        (else value)))
(define (ensure-directory path)
  (unless (file-exists? path)
    (ensure-directory (dirname path)) (mkdir path #o700)))
(define (write-settings path entries)
  (ensure-directory (dirname path))
  (let* ((port (mkstemp (string-append path ".XXXXXX")))
         (temporary (port-filename port)))
    (dynamic-wind
      (lambda () #t)
      (lambda ()
        (display (json-write (apply json-object
                        (map (lambda (entry) (cons (symbol->string (car entry))
                                                   (encoded (cdr entry)))) entries))) port)
        (newline port) (close-port port) (rename-file temporary path))
      (lambda ()
        (unless (port-closed? port) (close-port port))
        (when (file-exists? temporary) (delete-file temporary))))))
;; Keys that were renamed; files written by earlier builds still load.
(define (rename key) (if (eq? key 'show-tools) 'show-work key))
(define (load-settings! path source)
  (when (file-exists? path)
    (when (> (stat:size (stat path)) 32768) (error "settings file too large" path))
    (let ((value (call-with-input-file path (lambda (p) (json-read (get-string-all p))))))
      (unless (json-object? value) (error "settings must be an object" path))
      (for-each
       (lambda (entry)
         (let* ((key (rename (string->symbol (car entry)))) (value (decode key (cdr entry))))
           (unless (valid? key value) (error "invalid setting" path key))
           (cond
            ((eq? key 'run-allow) (allow-scope-set! source value) (refresh-run-allow!)
             (set! sources (acons key source (assq-delete-all key sources))))
            (else
             (set! preferences (acons key value (assq-delete-all key preferences)))
             (set! sources (acons key source (assq-delete-all key sources)))))))
       (json-object-entries value)))))
(define (settings-init! project-state session-state)
  (set! preferences '()) (set! sources '())
  (set! allow-lists '((user . ()) (project . ()) (session . ())))
  (set! project-file (string-append project-state "/settings.json"))
  (set! session-file (and session-state (string-append session-state "/settings.json")))
  (set! user-file (string-append (or (getenv "XDG_CONFIG_HOME")
                                   (string-append (getenv "HOME") "/.config"))
                               "/shift/settings.json"))
  (load-settings! user-file 'user)
  (load-settings! project-file 'project)
  (when session-file (load-settings! session-file 'session)))
(define (setting-ref generation key)
  (let ((entry (assq key preferences)))
    (cond (entry (cdr entry))
          ((assq key defaults) => cdr)
          (else (generation-ref generation key)))))
(define (settings-object generation)
  (apply json-object
    (map (lambda (key) (cons (symbol->string key) (encoded (setting-ref generation key))))
         (append bindings (map car defaults)))))
(define (settings-set! entries)
  (for-each (lambda (entry)
              (unless (valid? (car entry) (cdr entry)) (error "invalid setting" (car entry)))) entries)
  (let* ((allow (assq-ref entries 'run-allow))
         (session-allow (if allow
                            ;; Prefixes already allowed at another scope are not copied into the session.
                            (filter (lambda (prefix) (not (or (member prefix (or (assq-ref allow-lists 'user) '()))
                                                              (member prefix (or (assq-ref allow-lists 'project) '())))))
                                    allow)
                            (or (assq-ref allow-lists 'session) '())))
         (next (fold (lambda (entry acc)
                       (acons (car entry) (cdr entry) (assq-delete-all (car entry) acc)))
                     preferences entries)))
    ;; Only publish changes after durable storage succeeds.
    (when session-file
      (write-settings session-file (acons 'run-allow session-allow (assq-delete-all 'run-allow next))))
    (when allow (allow-scope-set! 'session session-allow))
    (set! preferences next)
    (when allow (refresh-run-allow!))
    (for-each (lambda (entry)
                (set! sources (acons (car entry) 'session (assq-delete-all (car entry) sources)))) entries)))
(define (setting-set! key value) (settings-set! (list (cons key value))))
;; For --set KEY=JSON: the value is parsed as JSON and decoded like a file.
(define (setting-set-json! key text)
  (let ((value (catch #t (lambda () (json-read text))
                 (lambda _ (error "setting value must be JSON" key text)))))
    (setting-set! key (decode key value))))
(define (settings-save! generation scope)
  (let ((path (if (eq? scope 'user) user-file project-file)))
    ;; Saving promotes preferences, and the whole effective allowlist, to that scope.
    (write-settings path (map (lambda (entry) (cons (string->symbol (car entry))
                                                   (decode (string->symbol (car entry)) (cdr entry))))
                             (json-object-entries (settings-object generation))))
    (allow-scope-set! scope (setting-ref generation 'run-allow))
    (allow-scope-set! 'session '())
    (when session-file (write-settings session-file (acons 'run-allow '() (assq-delete-all 'run-allow (file-entries session-file)))))
    path))
(define (setting-source key)
  (or (assq-ref sources key) 'default))
(define (settings-show generation)
  (for-each
   (lambda (key)
     (format #t "~a ~a (~a)~%" key (setting-ref generation key)
             (setting-source key)))
   (append bindings (map car defaults))))

(define (load-dotenv! path)
  ;; A deliberately small dotenv reader; no shell substitution or evaluation.
  (when (file-exists? path)
    (call-with-input-file path
      (lambda (port)
        (let loop ((line (get-line port)))
          (unless (eof-object? line)
            (let* ((line (string-trim-both line))
                   (line (if (string-prefix? "export " line) (substring line 7) line))
                   (equal (string-index line #\=)))
              (when (and equal (not (string-prefix? "#" line)))
                (let* ((name (string-trim-both (substring line 0 equal)))
                       (value (string-trim-both (substring line (+ equal 1)))))
                  (when (and (not (string-null? name))
                             (string-every (lambda (c) (or (char-alphabetic? c) (char-numeric? c) (char=? c #\_))) name)
                             (not (getenv name)))
                    (when (and (>= (string-length value) 2)
                               (memv (string-ref value 0) '(#\" #\'))
                               (char=? (string-ref value 0) (string-ref value (- (string-length value) 1))))
                      (set! value (substring value 1 (- (string-length value) 1))))
                    (setenv name value)))))
            (loop (get-line port))))))))
