(define-module (live-agent ui)
  #:use-module (ice-9 textual-ports)
  #:use-module (ice-9 threads)
  #:use-module (ice-9 format)
  #:use-module (srfi srfi-1)
  #:use-module (live-agent json)
  #:export (ui-init! ui-stop! ui-action! ui-state ui-emit! ui-connected?))

;; Presentation preferences are independent of agent generations and authority.
;; Scheme packs are bounded data, never evaluated as process code.
(define lock (make-mutex))
(define output-lock (make-mutex))
(define preferences (json-object))
(define presentation (json-object))
(define revision 0)
(define undo-stack '())
(define project-dir #f)
(define session-dir #f)
(define user-dir #f)
(define pack-path #f)
(define pack-text #f)
(define running? #f)
(define reader-thread #f)
(define watcher-thread #f)
(define event-port #f)
(define command-port #f)
(define (ui-connected?) (if event-port #t #f))
(define (ui-emit! type value)
  (when event-port
    (with-mutex output-lock
      (catch #t
        (lambda ()
          (display (json-write (json-object (cons "type" type) (cons "value" value))) event-port)
          (newline event-port) (force-output event-port))
        (lambda _ #f)))))
(define (merge-objects . objects)
  (apply json-object
    (fold (lambda (object result)
            (fold (lambda (entry result)
                    (cons entry (filter (lambda (old) (not (string=? (car old) (car entry)))) result)))
                  result (json-object-entries object))) '() objects)))
(define (safe-text? value limit)
  (and (string? value) (<= (string-length value) limit)
       (string-every (lambda (c) (and (>= (char->integer c) 32) (not (= (char->integer c) 127)))) value)))
(define colors '("background" "foreground" "accent" "secondary" "muted" "panel"))
(define (valid-entry? entry)
  (let ((key (car entry)) (value (cdr entry)))
    (cond
     ((member key colors) (and (integer? value) (exact? value) (<= 0 value 255)))
     ((string=? key "theme") (and (safe-text? value 64) (> (string-length value) 0)
                                  (string-every (lambda (c) (or (char-alphabetic? c) (char-numeric? c) (memv c '(#\- #\_)))) value)))
     ((string=? key "identity") (and (safe-text? value 64) (not (string-null? (string-trim-both value)))))
     ((string=? key "branding") (member value '("subtitle" "replace" "none")))
     ((string=? key "sidebar") (member value '("auto" "on" "off")))
     ((string=? key "placement") (member value '("left" "right" "top" "bottom" "modal")))
     ((string=? key "density") (member value '("compact" "comfortable")))
     ((string=? key "border") (member value '("thin" "heavy" "double" "none")))
     ((member key '("ascii" "metrics")) (boolean? value))
     ((string=? key "wordmark") (and (json-array? value) (<= 1 (length (json-array-items value)) 3)
       (every (lambda (v) (safe-text? v 64)) (json-array-items value))))
     ((string=? key "sections") (and (json-array? value) (<= (length (json-array-items value)) 4)
       (every (lambda (v) (member v '("session" "context" "files" "checks"))) (json-array-items value))
       (= (length (json-array-items value)) (length (delete-duplicates (json-array-items value))))))
     (else #f))))
(define (validate! object)
  (unless (and (json-object? object) (every valid-entry? (json-object-entries object)))
    (error "invalid UI preferences; use ui get for keys and current values"))
  object)
(define (defaults)
  (json-object (cons "theme" "acid") (cons "identity" (or (getenv "USER") "shift"))
    (cons "wordmark" (json-array "shift ///"))
    (cons "branding" "subtitle") (cons "sidebar" "auto") (cons "placement" "right")
    (cons "density" "comfortable") (cons "border" "thin") (cons "ascii" #f) (cons "metrics" #t)
    (cons "sections" (json-array "session" "context" "files" "checks"))
    (cons "background" 53) (cons "foreground" 255) (cons "accent" 154)
    (cons "secondary" 51) (cons "muted" 183) (cons "panel" 17)))
(define (bounded-read path)
  (when (> (stat:size (stat path)) 32768) (error "UI file exceeds 32 KiB" path))
  (call-with-input-file path get-string-all))
(define (load-preferences dir)
  (let ((path (and dir (string-append dir "/ui.json"))))
    (if (and path (file-exists? path)) (validate! (json-read (bounded-read path))) (json-object))))
(define (find-pack name)
  (or (find file-exists?
         (filter identity
           (list (and project-dir (string-append project-dir "/themes/" name ".scm"))
                 (and user-dir (string-append user-dir "/themes/" name ".scm"))
                 (string-append (or (getenv "SHIFT_INSTALL_ROOT") (getcwd)) "/themes/" name ".scm"))))
      (error "UI theme not found" name)))
(define (resolve-presentation prefs)
  (let* ((name (json-object-ref prefs "theme" "acid")) (path (find-pack name))
         (text (bounded-read path))
         (data (call-with-input-string text
                 (lambda (p) (let ((form (read p)))
                   (unless (eof-object? (read p)) (error "theme must contain one data form")) form))))
         (pack (begin
                 (unless (and (list? data) (every (lambda (e) (and (pair? e) (symbol? (car e)))) data))
                   (error "theme must be an association list"))
                 (apply json-object (map (lambda (e)
                   (cons (symbol->string (car e))
                         (if (memq (car e) '(sections wordmark)) (apply json-array (cdr e)) (cdr e)))) data)))))
    (validate! pack)
    (list (validate! (merge-objects (defaults) pack prefs)) path text)))
(define (mkdirs path)
  (unless (file-exists? path) (mkdirs (dirname path)) (mkdir path #o700)))
(define (save-object! dir object)
  (unless dir (error "UI settings need a named session or an explicit save scope"))
  (mkdirs dir)
  (let* ((path (string-append dir "/ui.json")) (port (mkstemp (string-append path ".XXXXXX")))
         (temporary (port-filename port)))
    (dynamic-wind (lambda () #t)
      (lambda () (display (json-write object) port) (newline port) (close-port port) (rename-file temporary path))
      (lambda () (unless (port-closed? port) (close-port port))
        (when (file-exists? temporary) (delete-file temporary))))))
(define (state-unlocked)
  (json-object (cons "revision" revision) (cons "config" presentation)
    (cons "theme_path" (or pack-path json-null))
    (cons "can_undo" (if (pair? undo-stack) #t #f))))
(define (ui-state) (with-mutex lock (state-unlocked)))
(define (activate! prefs resolved remember?)
  (when remember?
    (set! undo-stack (take (cons (list preferences presentation pack-path pack-text) undo-stack)
                          (min 32 (+ 1 (length undo-stack))))))
  (set! preferences prefs) (set! presentation (car resolved))
  (set! pack-path (cadr resolved)) (set! pack-text (caddr resolved))
  (set! revision (+ revision 1))
  (ui-emit! "ui" (state-unlocked)))
(define (ui-action! args)
  (with-mutex lock
    (let ((action (json-object-ref args "action" "get")))
      (cond
       ((string=? action "get") #t)
       ((string=? action "patch")
        (let* ((patch (validate! (json-object-ref args "patch")))
               (next (merge-objects preferences patch)) (resolved (resolve-presentation next)))
          (save-object! (or session-dir project-dir) next)
          (activate! next resolved #t)))
       ((string=? action "undo")
        (unless (pair? undo-stack) (error "no previous UI revision"))
        (let ((previous (car undo-stack)))
          (save-object! (or session-dir project-dir) (car previous))
          (set! undo-stack (cdr undo-stack))
          (activate! (car previous)
            (list (cadr previous) (caddr previous)
              (catch #t (lambda () (bounded-read (caddr previous))) (lambda _ (cadddr previous)))) #f)))
       ((string=? action "save")
        (let* ((scope (json-object-ref args "scope" "user"))
               (dir (cond ((string=? scope "user") user-dir)
                          ((string=? scope "project") project-dir)
                          (else (error "save scope must be user or project")))))
          (save-object! dir preferences)))
       ((string=? action "reload") (activate! preferences (resolve-presentation preferences) #t))
       (else (error "UI action must be get, patch, undo, save, or reload")))
      (state-unlocked))))
(define (inherited-port name mode)
  (let ((fd (getenv name)))
    (and fd (let ((p (fdopen (string->number fd) mode)))
              (fcntl p F_SETFD FD_CLOEXEC) p))))
(define (ui-init! project session)
  (set! project-dir project) (set! session-dir session)
  (set! user-dir (string-append (or (getenv "XDG_CONFIG_HOME") (string-append (getenv "HOME") "/.config")) "/shift"))
  (set! undo-stack '()) (set! revision 0)
  (set! event-port (inherited-port "SHIFT_UI_EVENT_FD" "w"))
  (set! command-port (inherited-port "SHIFT_UI_COMMAND_FD" "r"))
  (set! preferences
    (apply merge-objects
      (map (lambda (dir)
        (catch #t (lambda () (load-preferences dir))
          (lambda (key . args)
            (ui-emit! "ui-error" (format #f "UI preferences ignored at ~a: ~s" dir args))
            (json-object)))) (list user-dir project-dir session-dir))))
  (catch #t
    (lambda () (activate! preferences (resolve-presentation preferences) #f))
    (lambda (key . args)
      (set! presentation (defaults))
      (ui-emit! "ui" (state-unlocked))
      (ui-emit! "ui-error" (format #f "Theme rejected: ~s" args))))
  (set! running? #t)
  (when command-port
    (set! reader-thread (call-with-new-thread
      (lambda ()
        (let loop ()
          (let ((line (get-line command-port)))
            (unless (or (not running?) (eof-object? line))
              (catch #t
                (lambda () (ui-action! (json-read line)))
                (lambda (key . args) (ui-emit! "ui-error" (format #f "UI change rejected: ~s" args))))
              (loop))))))))
  (when event-port
    (set! watcher-thread (call-with-new-thread
      (lambda ()
        (let loop ((last-failure #f))
          (when running?
            (usleep 500000)
            (let ((failure (catch #t
              (lambda ()
                (with-mutex lock
                  (when (and pack-path (not (equal? (bounded-read pack-path) pack-text)))
                    (activate! preferences (resolve-presentation preferences) #t))) #f)
              (lambda (key . args) (format #f "Theme reload rejected: ~s" args)))))
              (when (and failure (not (equal? failure last-failure))) (ui-emit! "ui-error" failure))
              (loop failure))))))))
  (ui-state))
(define (ui-stop!)
  (set! running? #f)
  (when reader-thread (cancel-thread reader-thread) (set! reader-thread #f))
  (when watcher-thread (join-thread watcher-thread) (set! watcher-thread #f)))
