#!/usr/bin/env python3
"""Generate Ghostty terminal themes from the bundled Shift presentation packs.

Background, foreground, cursor, selection and the six semantic slots come from
themes/NAME.scm; the remaining ANSI slots are complementary picks listed here so
that a 16-color shell matches the pack. Run with --check to verify site/ghostty.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKS = ROOT / "themes"
OUT = ROOT / "site" / "ghostty"
NAMES = ("acid", "paddock", "blueprint", "qdos")

# ANSI slot -> pack role, or a complementary literal when the pack has no role.
PALETTES = {
    "acid": {
        "cursor": "accent", "selection_bg": "secondary", "selection_fg": "background",
        0: "panel", 8: "#6a4c93", 1: "negative", 9: "#ff8aa6", 2: "accent", 10: "#ccff4d",
        3: "#f6e05e", 11: "#fff08a", 4: "#8f7bff", 12: "muted", 5: "#e07aff", 13: "#f0a6ff",
        6: "secondary", 14: "positive", 7: "#d9cdef", 15: "foreground",
    },
    "paddock": {
        "cursor": "accent", "selection_bg": "accent", "selection_fg": "background",
        0: "foreground", 8: "muted", 1: "accent", 9: "#ff3b30", 2: "secondary", 10: "#2e8b2e",
        3: "#a86400", 11: "#c98a00", 4: "#1f4e9c", 12: "#3a6fc4", 5: "#8b1a6b", 13: "#b03a8c",
        6: "#007070", 14: "#1a9a9a", 7: "panel", 15: "background",
    },
    "blueprint": {
        "cursor": "accent", "selection_bg": "accent", "selection_fg": "background",
        0: "panel", 8: "#5f5fd7", 1: "#ff5f5f", 9: "#ff8787", 2: "#5fd75f", 10: "#87ff87",
        3: "accent", 11: "#ffffd7", 4: "secondary", 12: "#d7e7ff", 5: "#d787ff", 13: "#e7afff",
        6: "#5fffff", 14: "#87ffff", 7: "#d7d7d7", 15: "foreground",
    },
    "qdos": {
        "cursor": "accent", "selection_bg": "removed_background", "selection_fg": "accent",
        0: "background", 8: "#555555", 1: "removed_background", 9: "negative", 2: "muted", 10: "#8ff070",
        3: "accent", 11: "#fff08a", 4: "#3b6fd4", 12: "#6f9cff", 5: "#b05ac8", 13: "#d48ce8",
        6: "secondary", 14: "#8fe0dc", 7: "#c8c8c8", 15: "foreground",
    },
}
# Same defaults as src/live-agent/ui.scm for roles a pack leaves unset.
DEFAULTS = {"positive": "#64fff2", "negative": "#ff6588",
            "added_background": "#074e4a", "removed_background": "#45152f"}


def ansi_rgb(n):
    if n < 16:
        return ((0, 0, 0), (205, 0, 0), (0, 205, 0), (205, 205, 0), (0, 0, 238), (205, 0, 205), (0, 205, 205), (229, 229, 229),
                (127, 127, 127), (255, 0, 0), (0, 255, 0), (255, 255, 0), (92, 92, 255), (255, 0, 255), (0, 255, 255), (255, 255, 255))[n]
    if n >= 232:
        return (8 + (n - 232) * 10,) * 3
    value, levels = n - 16, (0, 95, 135, 175, 215, 255)
    return tuple(levels[i] for i in (value // 36, value // 6 % 6, value % 6))


def pack_colors(name):
    text = (PACKS / (name + ".scm")).read_text(encoding="utf-8")
    colors = dict(DEFAULTS)
    for key, hex_value, index in re.findall(r'\((\w+) \. (?:"(#[0-9a-fA-F]{6})"|(\d+))\)', text):
        colors[key] = hex_value.lower() if hex_value else "#%02x%02x%02x" % ansi_rgb(int(index))
    return colors


def render(name):
    colors, table = pack_colors(name), PALETTES[name]
    def color(spec):
        return spec if spec.startswith("#") else colors[spec]
    lines = [f"# Shift {name} — generated by scripts/ghostty_themes.py from themes/{name}.scm.",
             "# Install: copy to ~/.config/ghostty/themes/ and set `theme = shift-" + name + "`."]
    lines += [f"palette = {slot}={color(table[slot])}" for slot in range(16)]
    lines += [f"background = {colors['background']}", f"foreground = {colors['foreground']}",
              f"cursor-color = {color(table['cursor'])}", f"cursor-text = {colors['background']}",
              f"selection-background = {color(table['selection_bg'])}",
              f"selection-foreground = {color(table['selection_fg'])}"]
    return "\n".join(lines) + "\n"


def main(argv):
    check = "--check" in argv
    stale = []
    for name in NAMES:
        path, text = OUT / ("shift-" + name), render(name)
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            OUT.mkdir(exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print("wrote", path.relative_to(ROOT))
    if stale:
        print("ghostty themes out of date; run scripts/ghostty_themes.py:", ", ".join(stale), file=sys.stderr)
        return 1
    if check:
        print("Ghostty themes match the presentation packs.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
